## 1. Setup & Parse Arguments

In [1]:
# Auto-reload modules
%load_ext autoreload
%autoreload 2

import os
import numpy as np
import matplotlib.pyplot as plt
from pathlib import Path
from argparse import Namespace
import sys
from datetime import datetime
import gc
import torch
from train import train

# Check device
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Device: {device}")
if torch.cuda.is_available():
    print(f"GPU: {torch.cuda.get_device_name(0)}")
    print(f"GPU Memory: {torch.cuda.get_device_properties(0).total_memory / 1e9:.2f} GB")

Device: cuda
GPU: NVIDIA GeForce RTX 5080
GPU Memory: 17.09 GB

In [2]:
from config import (
    BATCH_SIZE, NUM_EPOCHS, LEARNING_RATE,
    MODE, FUSION_METHOD, FEATURE_MODE,
    CHECKPOINT_DIR, BEST_MODEL_NAME,
)

# ============================================================================
# CẤU HÌNH GRID SEARCH CHO DỰ ÁN DUAL-STREAM (FBANK + HANDCRAFTED)
# ============================================================================
ROOT_DIR = r"D:\extracted_features" # Thư mục gốc chứa các thư mục duration
durations = ['train_raw', 'train_vi_full', 'train_vi_7s', 'train_vi_3s', 'train_vi_5s']  # 'train_raw', 'train_vi_3s', 'train_vi_5s', 'train_vi_7s', 'train_vi_full'

# Các feature mode (Dựa vào config.py của bạn)
feature_modes = ["mfbe_pitch", "mfbe_only", "pitch_only"]
fusion_methods = ["concat", "cross_attention", "gating"]

def get_base_args():
    return Namespace(
        test_dir="D:/test", # Thay đổi nếu cần
        output_dir="./outputs",
        batch_size=128, # Dự án này dùng Conv1D nhỏ nên 64-128 là đẹp
        learning_rate=0.0001,
        lr_scheduler="plateau",
        num_epochs=50,
        optimizer="adam",
        weight_decay=0.001,
        aam_margin=0.3,
        aam_scale=30,
        mixed_precision=True,
        early_stop_patience=5,
        seed=42,
        device="cuda",
        
        # Biến gán động
        mode=3,
        exp_name="",
        base_dir="",
        feature_mode="",
        fusion_method="",
        duration=""
    )

def check_skip(exp_name):
    if os.path.exists(os.path.join("./outputs/experiments", exp_name, "results.json")):
        print(f"⏭ Bỏ qua: {exp_name} - Đã xong!")
        return True
    return False

In [3]:
import os
import random
import glob
from collections import defaultdict
import torch

def create_fixed_trials(val_dir, output_file, num_pairs=10000):
    """
    Generate val_trials.txt from shards using utterance filenames.
    Format: label utterance_filename1 utterance_filename2
    """
    print(f"  -> Scanning shards in {val_dir}...")
    
    # Find all FBank shards (or any shard directory)
    shard_dirs = glob.glob(os.path.join(val_dir, "*_shards"))
    if not shard_dirs:
        raise ValueError(f"No shard directories found in {val_dir}")
    
    shard_dir = shard_dirs[0]  # Use first found shard directory
    shard_files = sorted(glob.glob(os.path.join(shard_dir, "*.pt")))
    
    if not shard_files:
        raise ValueError(f"No .pt files found in {shard_dir}")
    
    # Extract all utterances grouped by speaker
    speaker_to_utterances = defaultdict(list)
    total_samples = 0
    
    for shard_path in shard_files:
        try:
            shard_data = torch.load(shard_path, weights_only=False, map_location='cpu')
            speaker_ids = shard_data.get("speaker_ids", [])
            filenames = shard_data.get("filenames", [])
            
            if len(speaker_ids) != len(filenames):
                continue
            
            for spk_id, utt_filename in zip(speaker_ids, filenames):
                speaker_to_utterances[spk_id].append(utt_filename)
                total_samples += 1
        except Exception as e:
            print(f"  ⚠ Error reading {shard_path}: {e}")
            continue
    
    print(f"  -> Loaded {total_samples} utterances from {len(speaker_to_utterances)} speakers")
    
    all_speakers = list(speaker_to_utterances.keys())
    valid_pos_speakers = [s for s in all_speakers if len(speaker_to_utterances[s]) >= 2]
    
    if not valid_pos_speakers or len(all_speakers) < 2:
        raise ValueError(f"Not enough speakers or utterances for trials. Got {len(valid_pos_speakers)} speakers with >=2 utts")
    
    trials = []
    
    # 1. Tạo Positive Pairs (cùng speaker)
    print(f"  -> Generating {num_pairs // 2} positive pairs...")
    for _ in range(num_pairs // 2):
        spk = random.choice(valid_pos_speakers)
        utt1, utt2 = random.sample(speaker_to_utterances[spk], 2)
        trials.append(f"1 {utt1} {utt2}")
    
    # 2. Tạo Negative Pairs (khác speaker)
    print(f"  -> Generating {num_pairs // 2} negative pairs...")
    for _ in range(num_pairs // 2):
        spk1, spk2 = random.sample(all_speakers, 2)
        utt1 = random.choice(speaker_to_utterances[spk1])
        utt2 = random.choice(speaker_to_utterances[spk2])
        trials.append(f"0 {utt1} {utt2}")
    
    random.shuffle(trials)
    
    os.makedirs(os.path.dirname(output_file), exist_ok=True)
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write('\n'.join(trials))
    
    print(f"✓ Đã tạo file trials cố định tại: {output_file} ({len(trials)} cặp)")

print("Kiểm tra và tạo file val_trials.txt cố định cho các tập dữ liệu...")
for dur in durations:
    val_dir = os.path.join(ROOT_DIR, dur)
    trial_file = os.path.join(val_dir, "val_trials.txt")
    if not os.path.exists(trial_file):
        print(f" -> Đang tạo trials cho {dur}...")
        try:
            create_fixed_trials(val_dir, trial_file, num_pairs=10000)
        except Exception as e:
            print(f" ❌ Error creating trials for {dur}: {e}")
    else:
        print(f" ✓ Trials file already exists for {dur}")
print("✓ Đã chuẩn bị xong toàn bộ Trials!")

Kiểm tra và tạo file val_trials.txt cố định cho các tập dữ liệu...
 ✓ Trials file already exists for train_raw
 ✓ Trials file already exists for train_vi_full
 ✓ Trials file already exists for train_vi_7s
 ✓ Trials file already exists for train_vi_3s
 ✓ Trials file already exists for train_vi_5s
✓ Đã chuẩn bị xong toàn bộ Trials!

## 2. Training

In [3]:
# 1. MODE 1: CHỈ DÙNG FBANK (5 Experiments)
for dur in durations:
    exp_name = f"Mode1_FBank_{dur}"
    if check_skip(exp_name): continue
    
    print(f"\n{'='*80}\nĐANG CHẠY: {exp_name}\n{'='*80}")
    args = get_base_args()
    args.mode = 1
    args.exp_name = exp_name
    args.duration = dur
    args.base_dir = os.path.join(ROOT_DIR, dur)
    args.feature_mode = "N/A"
    args.fusion_method = "N/A"
    
    train(args)
    gc.collect(); torch.cuda.empty_cache()

# 2. MODE 2: CHỈ DÙNG HANDCRAFTED (15 Experiments)
for dur in durations:
    for feat in feature_modes:
        exp_name = f"Mode2_HC_{dur}_{feat}"
        if check_skip(exp_name): continue
        
        print(f"\n{'='*80}\nĐANG CHẠY: {exp_name}\n{'='*80}")
        args = get_base_args()
        args.mode = 2
        args.exp_name = exp_name
        args.duration = dur
        args.base_dir = os.path.join(ROOT_DIR, dur)
        args.feature_mode = feat
        args.fusion_method = "N/A"
        
        train(args)
        gc.collect(); torch.cuda.empty_cache()

# 3. MODE 3: HYBRID FUSION (45 Experiments)
for dur in durations:
    for feat in feature_modes:
        for fusion in fusion_methods:
            exp_name = f"Mode3_{fusion}_{dur}_{feat}"
            if check_skip(exp_name): continue
            
            print(f"\n{'='*80}\nĐANG CHẠY: {exp_name}\n{'='*80}")
            args = get_base_args()
            args.mode = 3
            args.exp_name = exp_name
            args.duration = dur
            args.base_dir = os.path.join(ROOT_DIR, dur)
            args.feature_mode = feat
            args.fusion_method = fusion
            
            train(args)
            gc.collect(); torch.cuda.empty_cache()

print("\n🎉 TOÀN BỘ GRID SEARCH ĐÃ HOÀN TẤT THÀNH CÔNG!")

⏭ Bỏ qua: Mode1_FBank_train_raw - Đã xong!
⏭ Bỏ qua: Mode1_FBank_train_vi_full - Đã xong!
⏭ Bỏ qua: Mode1_FBank_train_vi_7s - Đã xong!
⏭ Bỏ qua: Mode1_FBank_train_vi_3s - Đã xong!
⏭ Bỏ qua: Mode1_FBank_train_vi_5s - Đã xong!
⏭ Bỏ qua: Mode2_HC_train_raw_mfbe_pitch - Đã xong!
⏭ Bỏ qua: Mode2_HC_train_raw_mfbe_only - Đã xong!
⏭ Bỏ qua: Mode2_HC_train_raw_pitch_only - Đã xong!
⏭ Bỏ qua: Mode2_HC_train_vi_full_mfbe_pitch - Đã xong!
⏭ Bỏ qua: Mode2_HC_train_vi_full_mfbe_only - Đã xong!
⏭ Bỏ qua: Mode2_HC_train_vi_full_pitch_only - Đã xong!
⏭ Bỏ qua: Mode2_HC_train_vi_7s_mfbe_pitch - Đã xong!
⏭ Bỏ qua: Mode2_HC_train_vi_7s_mfbe_only - Đã xong!
⏭ Bỏ qua: Mode2_HC_train_vi_7s_pitch_only - Đã xong!
⏭ Bỏ qua: Mode2_HC_train_vi_3s_mfbe_pitch - Đã xong!
⏭ Bỏ qua: Mode2_HC_train_vi_3s_mfbe_only - Đã xong!
⏭ Bỏ qua: Mode2_HC_train_vi_3s_pitch_only - Đã xong!
⏭ Bỏ qua: Mode2_HC_train_vi_5s_mfbe_pitch - Đã xong!
⏭ Bỏ qua: Mode2_HC_train_vi_5s_mfbe_only - Đã xong!
⏭ Bỏ qua: Mode2_HC_train_vi_5s_pitch_only - Đã xong!
⏭ Bỏ qua: Mode3_concat_train_raw_mfbe_pitch - Đã xong!
⏭ Bỏ qua: Mode3_cross_attention_train_raw_mfbe_pitch - Đã xong!
⏭ Bỏ qua: Mode3_gating_train_raw_mfbe_pitch - Đã xong!
⏭ Bỏ qua: Mode3_concat_train_raw_mfbe_only - Đã xong!
⏭ Bỏ qua: Mode3_cross_attention_train_raw_mfbe_only - Đã xong!
⏭ Bỏ qua: Mode3_gating_train_raw_mfbe_only - Đã xong!
⏭ Bỏ qua: Mode3_concat_train_raw_pitch_only - Đã xong!
⏭ Bỏ qua: Mode3_cross_attention_train_raw_pitch_only - Đã xong!
⏭ Bỏ qua: Mode3_gating_train_raw_pitch_only - Đã xong!
⏭ Bỏ qua: Mode3_concat_train_vi_full_mfbe_pitch - Đã xong!
⏭ Bỏ qua: Mode3_cross_attention_train_vi_full_mfbe_pitch - Đã xong!
⏭ Bỏ qua: Mode3_gating_train_vi_full_mfbe_pitch - Đã xong!
⏭ Bỏ qua: Mode3_concat_train_vi_full_mfbe_only - Đã xong!
⏭ Bỏ qua: Mode3_cross_attention_train_vi_full_mfbe_only - Đã xong!
⏭ Bỏ qua: Mode3_gating_train_vi_full_mfbe_only - Đã xong!
⏭ Bỏ qua: Mode3_concat_train_vi_full_pitch_only - Đã xong!
⏭ Bỏ qua: Mode3_cross_attention_train_vi_full_pitch_only - Đã xong!
⏭ Bỏ qua: Mode3_gating_train_vi_full_pitch_only - Đã xong!
⏭ Bỏ qua: Mode3_concat_train_vi_7s_mfbe_pitch - Đã xong!
⏭ Bỏ qua: Mode3_cross_attention_train_vi_7s_mfbe_pitch - Đã xong!
⏭ Bỏ qua: Mode3_gating_train_vi_7s_mfbe_pitch - Đã xong!
⏭ Bỏ qua: Mode3_concat_train_vi_7s_mfbe_only - Đã xong!
⏭ Bỏ qua: Mode3_cross_attention_train_vi_7s_mfbe_only - Đã xong!
⏭ Bỏ qua: Mode3_gating_train_vi_7s_mfbe_only - Đã xong!
⏭ Bỏ qua: Mode3_concat_train_vi_7s_pitch_only - Đã xong!
⏭ Bỏ qua: Mode3_cross_attention_train_vi_7s_pitch_only - Đã xong!
⏭ Bỏ qua: Mode3_gating_train_vi_7s_pitch_only - Đã xong!
⏭ Bỏ qua: Mode3_concat_train_vi_3s_mfbe_pitch - Đã xong!
⏭ Bỏ qua: Mode3_cross_attention_train_vi_3s_mfbe_pitch - Đã xong!
⏭ Bỏ qua: Mode3_gating_train_vi_3s_mfbe_pitch - Đã xong!
⏭ Bỏ qua: Mode3_concat_train_vi_3s_mfbe_only - Đã xong!
⏭ Bỏ qua: Mode3_cross_attention_train_vi_3s_mfbe_only - Đã xong!
⏭ Bỏ qua: Mode3_gating_train_vi_3s_mfbe_only - Đã xong!
⏭ Bỏ qua: Mode3_concat_train_vi_3s_pitch_only - Đã xong!
⏭ Bỏ qua: Mode3_cross_attention_train_vi_3s_pitch_only - Đã xong!
⏭ Bỏ qua: Mode3_gating_train_vi_3s_pitch_only - Đã xong!
⏭ Bỏ qua: Mode3_concat_train_vi_5s_mfbe_pitch - Đã xong!
⏭ Bỏ qua: Mode3_cross_attention_train_vi_5s_mfbe_pitch - Đã xong!
⏭ Bỏ qua: Mode3_gating_train_vi_5s_mfbe_pitch - Đã xong!
⏭ Bỏ qua: Mode3_concat_train_vi_5s_mfbe_only - Đã xong!
⏭ Bỏ qua: Mode3_cross_attention_train_vi_5s_mfbe_only - Đã xong!
⏭ Bỏ qua: Mode3_gating_train_vi_5s_mfbe_only - Đã xong!
⏭ Bỏ qua: Mode3_concat_train_vi_5s_pitch_only - Đã xong!
⏭ Bỏ qua: Mode3_cross_attention_train_vi_5s_pitch_only - Đã xong!
⏭ Bỏ qua: Mode3_gating_train_vi_5s_pitch_only - Đã xong!

🎉 TOÀN BỘ GRID SEARCH ĐÃ HOÀN TẤT THÀNH CÔNG!

## 3. Training Curves

In [ ]:
# Load TensorBoard extension
%load_ext tensorboard

# Chạy giao diện TensorBoard trỏ vào thư mục chứa tất cả các experiments
%tensorboard --logdir ./outputs/experiments

## 4. Test Results

In [1]:
import os
import json
from pathlib import Path
import pandas as pd
import numpy as np
import torch
import torch.nn.functional as F
from tqdm import tqdm

try:
    from model import get_model
    from metrics import compute_eer, compute_mindcf
except ImportError:
    from train.model import get_model
    from train.metrics import compute_eer, compute_mindcf

# ============================================================================
# 4. INFERENCE ALL MODELS ON MULTI TEST SETS (full, 3s, 5s, 7s, vi)
# ============================================================================

EXPERIMENTS_DIR = "./outputs/experiments"
LIST_GT_DIR = r"D:\test_o\list_gt"
DAT_ROOT = r"D:\test_o"

# Dừng toàn bộ ngay khi gặp lỗi để fix sớm
STOP_ON_ERROR = True

# Bỏ qua experiment đã infer thành công trước đó (status=ok trong file summary từng test set)
SKIP_ALREADY_INFERRED = True

# Thứ tự chạy test set
TEST_SET_CONFIGS = {
    "full": {
        "csv_name": "test_list_gt.csv",
        "data_dir": "full_length",
    },
    "3s": {
        "csv_name": "test_list_gt_3s.csv",
        "data_dir": "test_3s",
    },
    "5s": {
        "csv_name": "test_list_gt_5s.csv",
        "data_dir": "test_5s",
    },
    "7s": {
        "csv_name": "test_list_gt_7s.csv",
        "data_dir": "test_7s",
    },
    "vi": {
        "csv_name": "test_list_gt_vi.csv",
        "data_dir": "test_vi",
    },
}

# Tên file feature trong thư mục features của mỗi bộ test
FEATURE_FILENAMES = {
    "fbank": "FBank.pt",
    "mfbe_pitch": "MFBE_Pitch.pt",
    "mfbe_only": "Only_MFBE.pt",
    "pitch_only": "Only_Pitch.pt",
}

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
NUM_PAIRS_LIMIT = None   # None = chạy toàn bộ cặp trong CSV; hoặc set ví dụ 50000
P_TARGET = 0.05


def _load_pairs_csv(csv_path):
    if not os.path.exists(csv_path):
        raise FileNotFoundError(f"Không tìm thấy CSV: {csv_path}")

    raw = pd.read_csv(csv_path, header=None)
    if raw.shape[1] == 1:
        parts = raw[0].astype(str).str.strip().str.split(r"\s+", n=2, expand=True)
        if parts.shape[1] < 3:
            raise ValueError("CSV 1 cột nhưng không tách được đủ 3 trường: label path1 path2")
        df = pd.DataFrame({"label": parts[0], "path1": parts[1], "path2": parts[2]})
    else:
        df = pd.DataFrame({"label": raw.iloc[:, 0], "path1": raw.iloc[:, 1], "path2": raw.iloc[:, 2]})

    df["label"] = df["label"].astype(int)
    df["path1"] = df["path1"].astype(str).str.strip()
    df["path2"] = df["path2"].astype(str).str.strip()
    return df


def _normalize_feat_tensor(feat):
    if not torch.is_tensor(feat):
        feat = torch.tensor(feat)

    feat = feat.float()
    if feat.dim() == 1:
        feat = feat.unsqueeze(0)   # (C, T)
    elif feat.dim() == 3 and feat.shape[0] == 1:
        feat = feat.squeeze(0)      # (C, T)
    elif feat.dim() != 2:
        raise ValueError(f"Feature tensor shape không hợp lệ: {tuple(feat.shape)}")
    return feat


def _candidate_keys(path_text):
    p = str(path_text).replace('\\', '/').strip()
    base = os.path.basename(p)
    stem = os.path.splitext(base)[0]
    rel = p.lstrip('./')
    candidates = [p, rel, base, stem]
    # unique giữ thứ tự
    seen = set()
    out = []
    for k in candidates:
        if k not in seen:
            out.append(k)
            seen.add(k)
    return out


def _get_feature_from_dict(feat_dict, path_text):
    for key in _candidate_keys(path_text):
        if key in feat_dict:
            return feat_dict[key]
    return None


def _evaluate_one_model(
    model,
    mode,
    pairs_df,
    device,
    fbank_dict=None,
    hand_dict=None,
    p_target=0.05,
    num_pairs_limit=None,
):
    model.eval()
    rows = pairs_df if num_pairs_limit is None else pairs_df.iloc[:num_pairs_limit]

    cache = {}
    missing_pairs = 0
    scores = []
    labels = []

    def get_embedding(utt_path):
        if utt_path in cache:
            return cache[utt_path]

        inputs = {}
        if mode in [1, 3]:
            if fbank_dict is None:
                raise ValueError("Model mode cần FBank nhưng chưa cung cấp FBank dict")
            f_feat = _get_feature_from_dict(fbank_dict, utt_path)
            if f_feat is None:
                cache[utt_path] = None
                return None
            f_feat = _normalize_feat_tensor(f_feat).unsqueeze(0).to(device)
            inputs["fbank"] = f_feat

        if mode in [2, 3]:
            if hand_dict is None:
                raise ValueError("Model mode cần handcrafted nhưng chưa cung cấp file .pt phù hợp")
            h_feat = _get_feature_from_dict(hand_dict, utt_path)
            if h_feat is None:
                cache[utt_path] = None
                return None
            h_feat = _normalize_feat_tensor(h_feat).unsqueeze(0).to(device)
            inputs["handcrafted"] = h_feat

        with torch.no_grad():
            _, emb = model(**inputs)
            emb = F.normalize(emb, p=2, dim=1).squeeze(0).cpu()

        cache[utt_path] = emb
        return emb

    for row in tqdm(rows.itertuples(index=False), total=len(rows), leave=False):
        emb1 = get_embedding(row.path1)
        emb2 = get_embedding(row.path2)
        if emb1 is None or emb2 is None:
            missing_pairs += 1
            continue

        score = float(torch.dot(emb1, emb2).item())
        scores.append(score)
        labels.append(int(row.label))

    if len(scores) == 0:
        raise ValueError("Không có cặp hợp lệ nào để tính metric")

    eer, _ = compute_eer(labels, scores)
    mindcf, _ = compute_mindcf(labels, scores, p_target=p_target)

    return {
        "num_pairs_used": len(scores),
        "num_pairs_missing": missing_pairs,
        "eer_percent": float(eer * 100),
        "mindcf": float(mindcf),
    }


def _build_test_assets():
    assets = {}
    for test_set, cfg in TEST_SET_CONFIGS.items():
        csv_path = Path(LIST_GT_DIR) / cfg["csv_name"]
        if not csv_path.exists():
            raise FileNotFoundError(f"[{test_set}] Không tìm thấy file list_gt: {csv_path}")

        features_dir = Path(DAT_ROOT) / cfg["data_dir"] / "features"
        if not features_dir.exists():
            raise FileNotFoundError(f"[{test_set}] Không tìm thấy thư mục features: {features_dir}")

        fbank_path = features_dir / FEATURE_FILENAMES["fbank"]
        if not fbank_path.exists():
            raise FileNotFoundError(f"[{test_set}] Thiếu file FBank: {fbank_path}")

        hand_map = {
            "mfbe_pitch": features_dir / FEATURE_FILENAMES["mfbe_pitch"],
            "mfbe_only": features_dir / FEATURE_FILENAMES["mfbe_only"],
            "pitch_only": features_dir / FEATURE_FILENAMES["pitch_only"],
        }
        for feat_mode, feat_path in hand_map.items():
            if not feat_path.exists():
                raise FileNotFoundError(f"[{test_set}] Thiếu file {feat_mode}: {feat_path}")

        assets[test_set] = {
            "csv_path": csv_path,
            "fbank_path": fbank_path,
            "hand_map": hand_map,
        }

    return assets


def _load_existing_set_results(set_save_path):
    if not set_save_path.exists():
        return []

    prev_df = pd.read_csv(set_save_path)
    required_cols = {"experiment", "status"}
    if not required_cols.issubset(set(prev_df.columns)):
        print(f"⚠ File cũ thiếu cột cần thiết, sẽ bỏ qua để chạy lại: {set_save_path}")
        return []

    prev_rows = prev_df.to_dict("records")
    print(f"📌 Tìm thấy kết quả cũ: {set_save_path} ({len(prev_rows)} dòng)")
    return prev_rows


def run_all_experiments_inference_multi_test():
    exp_root = Path(EXPERIMENTS_DIR)
    if not exp_root.exists():
        raise FileNotFoundError(f"Không tìm thấy thư mục experiments: {exp_root}")

    test_assets = _build_test_assets()
    exp_dirs = sorted([d for d in exp_root.iterdir() if d.is_dir()])
    print(f"\n🚀 Bắt đầu inference cho {len(exp_dirs)} experiments trên {len(test_assets)} test sets...")

    all_results = []

    for test_set, assets in test_assets.items():
        print(f"\n{'='*100}\nĐANG CHẠY TEST SET: {test_set}\n{'='*100}")

        pairs_df = _load_pairs_csv(str(assets["csv_path"]))
        print(f"✅ [{test_set}] Loaded CSV pairs: {len(pairs_df)} rows from {assets['csv_path']}")

        fbank_dict = torch.load(assets["fbank_path"], map_location="cpu")
        if not isinstance(fbank_dict, dict):
            raise ValueError(f"[{test_set}] FBank file phải là dict key->tensor: {assets['fbank_path']}")

        set_save_path = exp_root / f"inference_test_o_summary_{test_set}.csv"
        set_results = _load_existing_set_results(set_save_path)
        done_ok_experiments = {
            str(row.get("experiment", ""))
            for row in set_results
            if str(row.get("status", "")).strip().lower() == "ok" and str(row.get("experiment", "")).strip()
        }

        handcrafted_cache = {}

        for exp_dir in tqdm(exp_dirs, desc=f"Experiments ({test_set})"):
            config_path = exp_dir / "config.json"
            checkpoint_path = exp_dir / "best_model.pth"
            if not checkpoint_path.exists():
                checkpoint_path = exp_dir / "best_eer_model.pth"

            if (not config_path.exists()) or (not checkpoint_path.exists()):
                continue

            if SKIP_ALREADY_INFERRED and exp_dir.name in done_ok_experiments:
                print(f"⏭ [{test_set}] Skip đã infer: {exp_dir.name}")
                continue

            with open(config_path, "r", encoding="utf-8") as f:
                cfg = json.load(f)

            mode = int(cfg.get("mode", 3))
            feature_mode = str(cfg.get("feature_mode", "mfbe_pitch"))
            fusion_method = str(cfg.get("fusion_method", "concat"))

            hand_dict = None
            if mode in [2, 3]:
                hand_path = assets["hand_map"].get(feature_mode)
                if hand_path is None:
                    raise ValueError(f"[{test_set}] feature_mode không hỗ trợ: {feature_mode}")

                hand_key = str(hand_path)
                if hand_key not in handcrafted_cache:
                    handcrafted_cache[hand_key] = torch.load(hand_path, map_location="cpu")
                    if not isinstance(handcrafted_cache[hand_key], dict):
                        raise ValueError(f"[{test_set}] File handcrafted không đúng định dạng dict: {hand_path}")
                hand_dict = handcrafted_cache[hand_key]

            try:
                model = get_model(
                    num_speakers=1,
                    device=str(DEVICE),
                    mode=mode,
                    fusion_method=fusion_method,
                    feature_mode=feature_mode,
                )
                ckpt = torch.load(checkpoint_path, map_location=DEVICE)
                state_dict = ckpt["model_state_dict"] if isinstance(ckpt, dict) and "model_state_dict" in ckpt else ckpt
                model.load_state_dict(state_dict, strict=True)

                metrics = _evaluate_one_model(
                    model=model,
                    mode=mode,
                    pairs_df=pairs_df,
                    device=DEVICE,
                    fbank_dict=fbank_dict,
                    hand_dict=hand_dict,
                    p_target=P_TARGET,
                    num_pairs_limit=NUM_PAIRS_LIMIT,
                )

                row = {
                    "test_set": test_set,
                    "experiment": exp_dir.name,
                    "mode": mode,
                    "feature_mode": feature_mode,
                    "fusion_method": fusion_method,
                    "checkpoint": checkpoint_path.name,
                    "status": "ok",
                    "eer_percent": round(metrics["eer_percent"], 4),
                    "mindcf": round(metrics["mindcf"], 6),
                    "pairs_used": metrics["num_pairs_used"],
                    "pairs_missing": metrics["num_pairs_missing"],
                }
                set_results.append(row)
                done_ok_experiments.add(exp_dir.name)

                print(
                    f"✅ [{test_set}] {exp_dir.name} | "
                    f"EER={row['eer_percent']:.4f}% | minDCF={row['mindcf']:.6f} | "
                    f"pairs_used={row['pairs_used']} | missing={row['pairs_missing']}"
                )

            except Exception as ex:
                err_row = {
                    "test_set": test_set,
                    "experiment": exp_dir.name,
                    "mode": mode,
                    "feature_mode": feature_mode,
                    "fusion_method": fusion_method,
                    "status": f"error: {type(ex).__name__}",
                    "error_message": str(ex),
                }
                set_results.append(err_row)
                print(f"❌ [{test_set}] {exp_dir.name} | {type(ex).__name__}: {ex}")

                if STOP_ON_ERROR:
                    raise RuntimeError(
                        f"Dừng do lỗi tại test_set={test_set}, experiment={exp_dir.name}: {type(ex).__name__}: {ex}"
                    ) from ex

        if not set_results:
            raise RuntimeError(f"[{test_set}] Không có experiment nào được đánh giá.")

        set_df = pd.DataFrame(set_results)
        ok_set_df = set_df[set_df["status"] == "ok"].copy()
        if len(ok_set_df) > 0:
            ok_set_df = ok_set_df.sort_values(["eer_percent", "mindcf"], ascending=[True, True])
            print(f"\n✅ TOP RESULTS [{test_set}] (status=ok)")
            display(ok_set_df.head(20))
        else:
            raise RuntimeError(f"[{test_set}] Không có experiment nào chạy thành công.")

        set_df.to_csv(set_save_path, index=False, encoding="utf-8-sig")
        print(f"💾 [{test_set}] Đã lưu bảng tổng hợp: {set_save_path}")

        all_results.extend(set_results)

    all_df = pd.DataFrame(all_results)
    ok_all_df = all_df[all_df["status"] == "ok"].copy()
    if len(ok_all_df) > 0:
        ok_all_df = ok_all_df.sort_values(["eer_percent", "mindcf"], ascending=[True, True])
        print("\n✅ TOP RESULTS ALL TEST SETS (status=ok, sort by EER asc)")
        display(ok_all_df.head(30))
    else:
        raise RuntimeError("Không có kết quả thành công nào ở toàn bộ test sets.")

    all_save_path = exp_root / "inference_test_o_summary_all_sets.csv"
    all_df.to_csv(all_save_path, index=False, encoding="utf-8-sig")
    print(f"\n💾 Đã lưu bảng tổng hợp toàn bộ test sets: {all_save_path}")

    return all_df


results_df = run_all_experiments_inference_multi_test()

🚀 Bắt đầu inference cho 65 experiments trên 5 test sets...

====================================================================================================
ĐANG CHẠY TEST SET: full
====================================================================================================
✅ [full] Loaded CSV pairs: 9895 rows from D:\test_o\list_gt\test_list_gt.csv

Experiments (full):   0%|          | 0/65 [00:00<?, ?it/s]

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 1 (1=Main, 2=Handcrafted, 3=Fusion)
  Num speakers: 1
  Trainable parameters: 7,962,176
======================================================================

Experiments (full):   2%|▏         | 1/65 [01:04<1:08:28, 64.19s/it]

✅ [full] Mode1_FBank_train_raw | EER=4.1253% | minDCF=0.540997 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 1 (1=Main, 2=Handcrafted, 3=Fusion)
  Num speakers: 1
  Trainable parameters: 7,962,176
======================================================================

Experiments (full):   3%|▎         | 2/65 [02:03<1:04:05, 61.05s/it]

✅ [full] Mode1_FBank_train_vi_3s | EER=4.3687% | minDCF=0.629391 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 1 (1=Main, 2=Handcrafted, 3=Fusion)
  Num speakers: 1
  Trainable parameters: 7,962,176
======================================================================

Experiments (full):   5%|▍         | 3/65 [03:01<1:01:41, 59.70s/it]

✅ [full] Mode1_FBank_train_vi_5s | EER=4.5716% | minDCF=0.574253 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 1 (1=Main, 2=Handcrafted, 3=Fusion)
  Num speakers: 1
  Trainable parameters: 7,962,176
======================================================================

Experiments (full):   6%|▌         | 4/65 [04:01<1:00:46, 59.78s/it]

✅ [full] Mode1_FBank_train_vi_7s | EER=6.6613% | minDCF=0.728603 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 1 (1=Main, 2=Handcrafted, 3=Fusion)
  Num speakers: 1
  Trainable parameters: 7,962,176
======================================================================

Experiments (full):   8%|▊         | 5/65 [05:00<59:47, 59.78s/it]

✅ [full] Mode1_FBank_train_vi_full | EER=4.4160% | minDCF=0.604177 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 2 (1=Main, 2=Handcrafted, 3=Fusion)
  Handcrafted Feature: MFBE_ONLY
  Num speakers: 1
  Trainable parameters: 1,050,752
======================================================================

Experiments (full):   9%|▉         | 6/65 [05:14<43:28, 44.22s/it]

✅ [full] Mode2_HC_train_raw_mfbe_only | EER=43.9035% | minDCF=1.000000 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 2 (1=Main, 2=Handcrafted, 3=Fusion)
  Handcrafted Feature: MFBE_PITCH
  Num speakers: 1
  Trainable parameters: 1,051,136
======================================================================

Experiments (full):  11%|█         | 7/65 [05:27<32:55, 34.06s/it]

✅ [full] Mode2_HC_train_raw_mfbe_pitch | EER=42.1857% | minDCF=1.000000 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 2 (1=Main, 2=Handcrafted, 3=Fusion)
  Handcrafted Feature: PITCH_ONLY
  Num speakers: 1
  Trainable parameters: 1,020,416
======================================================================

Experiments (full):  12%|█▏        | 8/65 [05:38<25:14, 26.57s/it]

✅ [full] Mode2_HC_train_raw_pitch_only | EER=46.9737% | minDCF=0.999591 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 2 (1=Main, 2=Handcrafted, 3=Fusion)
  Handcrafted Feature: MFBE_ONLY
  Num speakers: 1
  Trainable parameters: 1,050,752
======================================================================

Experiments (full):  14%|█▍        | 9/65 [05:49<20:17, 21.75s/it]

✅ [full] Mode2_HC_train_vi_3s_mfbe_only | EER=41.9963% | minDCF=1.000000 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 2 (1=Main, 2=Handcrafted, 3=Fusion)
  Handcrafted Feature: MFBE_PITCH
  Num speakers: 1
  Trainable parameters: 1,051,136
======================================================================

Experiments (full):  15%|█▌        | 10/65 [06:00<16:48, 18.33s/it]

✅ [full] Mode2_HC_train_vi_3s_mfbe_pitch | EER=44.6134% | minDCF=1.000000 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 2 (1=Main, 2=Handcrafted, 3=Fusion)
  Handcrafted Feature: PITCH_ONLY
  Num speakers: 1
  Trainable parameters: 1,020,416
======================================================================

Experiments (full):  17%|█▋        | 11/65 [06:09<14:03, 15.61s/it]

✅ [full] Mode2_HC_train_vi_3s_pitch_only | EER=42.5577% | minDCF=1.000000 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 2 (1=Main, 2=Handcrafted, 3=Fusion)
  Handcrafted Feature: MFBE_ONLY
  Num speakers: 1
  Trainable parameters: 1,050,752
======================================================================

Experiments (full):  18%|█▊        | 12/65 [06:21<12:36, 14.28s/it]

✅ [full] Mode2_HC_train_vi_5s_mfbe_only | EER=40.9684% | minDCF=1.000000 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 2 (1=Main, 2=Handcrafted, 3=Fusion)
  Handcrafted Feature: MFBE_PITCH
  Num speakers: 1
  Trainable parameters: 1,051,136
======================================================================

Experiments (full):  20%|██        | 13/65 [06:31<11:23, 13.15s/it]

✅ [full] Mode2_HC_train_vi_5s_mfbe_pitch | EER=41.7732% | minDCF=1.000000 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 2 (1=Main, 2=Handcrafted, 3=Fusion)
  Handcrafted Feature: PITCH_ONLY
  Num speakers: 1
  Trainable parameters: 1,020,416
======================================================================

Experiments (full):  22%|██▏       | 14/65 [06:40<10:10, 11.97s/it]

✅ [full] Mode2_HC_train_vi_5s_pitch_only | EER=44.6000% | minDCF=0.999591 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 2 (1=Main, 2=Handcrafted, 3=Fusion)
  Handcrafted Feature: MFBE_ONLY
  Num speakers: 1
  Trainable parameters: 1,050,752
======================================================================

Experiments (full):  23%|██▎       | 15/65 [06:51<09:45, 11.71s/it]

✅ [full] Mode2_HC_train_vi_7s_mfbe_only | EER=44.0386% | minDCF=1.000000 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 2 (1=Main, 2=Handcrafted, 3=Fusion)
  Handcrafted Feature: MFBE_PITCH
  Num speakers: 1
  Trainable parameters: 1,051,136
======================================================================

Experiments (full):  25%|██▍       | 16/65 [07:02<09:19, 11.42s/it]

✅ [full] Mode2_HC_train_vi_7s_mfbe_pitch | EER=44.8841% | minDCF=1.000000 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 2 (1=Main, 2=Handcrafted, 3=Fusion)
  Handcrafted Feature: PITCH_ONLY
  Num speakers: 1
  Trainable parameters: 1,020,416
======================================================================

Experiments (full):  26%|██▌       | 17/65 [07:11<08:37, 10.77s/it]

✅ [full] Mode2_HC_train_vi_7s_pitch_only | EER=38.8315% | minDCF=1.000000 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 2 (1=Main, 2=Handcrafted, 3=Fusion)
  Handcrafted Feature: MFBE_ONLY
  Num speakers: 1
  Trainable parameters: 1,050,752
======================================================================

Experiments (full):  28%|██▊       | 18/65 [07:23<08:33, 10.93s/it]

✅ [full] Mode2_HC_train_vi_full_mfbe_only | EER=43.8223% | minDCF=0.999591 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 2 (1=Main, 2=Handcrafted, 3=Fusion)
  Handcrafted Feature: MFBE_PITCH
  Num speakers: 1
  Trainable parameters: 1,051,136
======================================================================

Experiments (full):  29%|██▉       | 19/65 [07:34<08:22, 10.93s/it]

✅ [full] Mode2_HC_train_vi_full_mfbe_pitch | EER=43.9913% | minDCF=1.000000 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 2 (1=Main, 2=Handcrafted, 3=Fusion)
  Handcrafted Feature: PITCH_ONLY
  Num speakers: 1
  Trainable parameters: 1,020,416
======================================================================

Experiments (full):  31%|███       | 20/65 [07:43<07:49, 10.43s/it]

✅ [full] Mode2_HC_train_vi_full_pitch_only | EER=41.6582% | minDCF=0.999591 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CONCAT
  Handcrafted Feature: MFBE_ONLY
  Num speakers: 1
  Trainable parameters: 9,537,728
======================================================================

Experiments (full):  32%|███▏      | 21/65 [08:59<22:04, 30.10s/it]

✅ [full] Mode3_concat_train_raw_mfbe_only | EER=4.3349% | minDCF=0.570964 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CONCAT
  Handcrafted Feature: MFBE_PITCH
  Num speakers: 1
  Trainable parameters: 9,538,112
======================================================================

Experiments (full):  34%|███▍      | 22/65 [10:13<31:08, 43.45s/it]

✅ [full] Mode3_concat_train_raw_mfbe_pitch | EER=4.9030% | minDCF=0.553536 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CONCAT
  Handcrafted Feature: PITCH_ONLY
  Num speakers: 1
  Trainable parameters: 9,507,392
======================================================================

Experiments (full):  35%|███▌      | 23/65 [11:27<36:38, 52.35s/it]

✅ [full] Mode3_concat_train_raw_pitch_only | EER=4.4499% | minDCF=0.650571 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CONCAT
  Handcrafted Feature: MFBE_ONLY
  Num speakers: 1
  Trainable parameters: 9,537,728
======================================================================

Experiments (full):  37%|███▋      | 24/65 [12:42<40:26, 59.19s/it]

✅ [full] Mode3_concat_train_vi_3s_mfbe_only | EER=24.8935% | minDCF=1.000000 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CONCAT
  Handcrafted Feature: MFBE_PITCH
  Num speakers: 1
  Trainable parameters: 9,538,112
======================================================================

Experiments (full):  38%|███▊      | 25/65 [13:57<42:44, 64.11s/it]

✅ [full] Mode3_concat_train_vi_3s_mfbe_pitch | EER=18.8071% | minDCF=0.999591 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CONCAT
  Handcrafted Feature: PITCH_ONLY
  Num speakers: 1
  Trainable parameters: 9,507,392
======================================================================

Experiments (full):  40%|████      | 26/65 [15:10<43:23, 66.76s/it]

✅ [full] Mode3_concat_train_vi_3s_pitch_only | EER=5.2749% | minDCF=0.632227 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CONCAT
  Handcrafted Feature: MFBE_ONLY
  Num speakers: 1
  Trainable parameters: 9,537,728
======================================================================

Experiments (full):  42%|████▏     | 27/65 [16:25<43:46, 69.13s/it]

✅ [full] Mode3_concat_train_vi_5s_mfbe_only | EER=27.9570% | minDCF=1.000000 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CONCAT
  Handcrafted Feature: MFBE_PITCH
  Num speakers: 1
  Trainable parameters: 9,538,112
======================================================================

Experiments (full):  43%|████▎     | 28/65 [17:39<43:37, 70.74s/it]

✅ [full] Mode3_concat_train_vi_5s_mfbe_pitch | EER=31.6832% | minDCF=0.999591 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CONCAT
  Handcrafted Feature: PITCH_ONLY
  Num speakers: 1
  Trainable parameters: 9,507,392
======================================================================

Experiments (full):  45%|████▍     | 29/65 [18:53<42:59, 71.66s/it]

✅ [full] Mode3_concat_train_vi_5s_pitch_only | EER=5.8024% | minDCF=0.634716 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CONCAT
  Handcrafted Feature: MFBE_ONLY
  Num speakers: 1
  Trainable parameters: 9,537,728
======================================================================

Experiments (full):  46%|████▌     | 30/65 [20:08<42:20, 72.58s/it]

✅ [full] Mode3_concat_train_vi_7s_mfbe_only | EER=35.5178% | minDCF=1.000000 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CONCAT
  Handcrafted Feature: MFBE_PITCH
  Num speakers: 1
  Trainable parameters: 9,538,112
======================================================================

Experiments (full):  48%|████▊     | 31/65 [21:23<41:30, 73.25s/it]

✅ [full] Mode3_concat_train_vi_7s_mfbe_pitch | EER=39.4603% | minDCF=1.000000 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CONCAT
  Handcrafted Feature: PITCH_ONLY
  Num speakers: 1
  Trainable parameters: 9,507,392
======================================================================

Experiments (full):  49%|████▉     | 32/65 [22:36<40:15, 73.21s/it]

✅ [full] Mode3_concat_train_vi_7s_pitch_only | EER=14.5872% | minDCF=0.998366 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CONCAT
  Handcrafted Feature: MFBE_ONLY
  Num speakers: 1
  Trainable parameters: 9,537,728
======================================================================

Experiments (full):  51%|█████     | 33/65 [23:51<39:18, 73.70s/it]

✅ [full] Mode3_concat_train_vi_full_mfbe_only | EER=5.5522% | minDCF=0.688194 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CONCAT
  Handcrafted Feature: MFBE_PITCH
  Num speakers: 1
  Trainable parameters: 9,538,112
======================================================================

Experiments (full):  52%|█████▏    | 34/65 [25:05<38:08, 73.84s/it]

✅ [full] Mode3_concat_train_vi_full_mfbe_pitch | EER=3.9291% | minDCF=0.594915 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CONCAT
  Handcrafted Feature: PITCH_ONLY
  Num speakers: 1
  Trainable parameters: 9,507,392
======================================================================

Experiments (full):  54%|█████▍    | 35/65 [26:18<36:47, 73.58s/it]

✅ [full] Mode3_concat_train_vi_full_pitch_only | EER=5.1532% | minDCF=0.656428 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CROSS_ATTENTION
  Handcrafted Feature: MFBE_ONLY
  Num speakers: 1
  Trainable parameters: 9,801,920
======================================================================

Experiments (full):  55%|█████▌    | 36/65 [27:36<36:11, 74.88s/it]

✅ [full] Mode3_cross_attention_train_raw_mfbe_only | EER=4.1793% | minDCF=0.586109 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CROSS_ATTENTION
  Handcrafted Feature: MFBE_PITCH
  Num speakers: 1
  Trainable parameters: 9,802,304
======================================================================

Experiments (full):  57%|█████▋    | 37/65 [28:52<35:11, 75.41s/it]

✅ [full] Mode3_cross_attention_train_raw_mfbe_pitch | EER=5.0787% | minDCF=0.593095 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CROSS_ATTENTION
  Handcrafted Feature: PITCH_ONLY
  Num speakers: 1
  Trainable parameters: 9,771,584
======================================================================

Experiments (full):  58%|█████▊    | 38/65 [30:08<33:55, 75.38s/it]

✅ [full] Mode3_cross_attention_train_raw_pitch_only | EER=4.7407% | minDCF=0.578573 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CROSS_ATTENTION
  Handcrafted Feature: MFBE_ONLY
  Num speakers: 1
  Trainable parameters: 9,801,920
======================================================================

Experiments (full):  60%|██████    | 39/65 [31:25<32:53, 75.91s/it]

✅ [full] Mode3_cross_attention_train_vi_3s_mfbe_only | EER=4.2199% | minDCF=0.584847 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CROSS_ATTENTION
  Handcrafted Feature: MFBE_PITCH
  Num speakers: 1
  Trainable parameters: 9,802,304
======================================================================

Experiments (full):  62%|██████▏   | 40/65 [32:42<31:47, 76.31s/it]

✅ [full] Mode3_cross_attention_train_vi_3s_mfbe_pitch | EER=4.2537% | minDCF=0.568602 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CROSS_ATTENTION
  Handcrafted Feature: PITCH_ONLY
  Num speakers: 1
  Trainable parameters: 9,771,584
======================================================================

Experiments (full):  63%|██████▎   | 41/65 [33:58<30:30, 76.26s/it]

✅ [full] Mode3_cross_attention_train_vi_3s_pitch_only | EER=4.1320% | minDCF=0.558424 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CROSS_ATTENTION
  Handcrafted Feature: MFBE_ONLY
  Num speakers: 1
  Trainable parameters: 9,801,920
======================================================================

Experiments (full):  65%|██████▍   | 42/65 [35:10<28:41, 74.84s/it]

✅ [full] Mode3_cross_attention_train_vi_5s_mfbe_only | EER=4.2470% | minDCF=0.572155 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CROSS_ATTENTION
  Handcrafted Feature: MFBE_PITCH
  Num speakers: 1
  Trainable parameters: 9,802,304
======================================================================

Experiments (full):  66%|██████▌   | 43/65 [36:25<27:32, 75.09s/it]

✅ [full] Mode3_cross_attention_train_vi_5s_mfbe_pitch | EER=4.3755% | minDCF=0.581843 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CROSS_ATTENTION
  Handcrafted Feature: PITCH_ONLY
  Num speakers: 1
  Trainable parameters: 9,771,584
======================================================================

Experiments (full):  68%|██████▊   | 44/65 [37:39<26:06, 74.61s/it]

✅ [full] Mode3_cross_attention_train_vi_5s_pitch_only | EER=4.6122% | minDCF=0.590252 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CROSS_ATTENTION
  Handcrafted Feature: MFBE_ONLY
  Num speakers: 1
  Trainable parameters: 9,801,920
======================================================================

Experiments (full):  69%|██████▉   | 45/65 [38:48<24:16, 72.83s/it]

✅ [full] Mode3_cross_attention_train_vi_7s_mfbe_only | EER=17.2855% | minDCF=0.982286 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CROSS_ATTENTION
  Handcrafted Feature: MFBE_PITCH
  Num speakers: 1
  Trainable parameters: 9,802,304
======================================================================

Experiments (full):  71%|███████   | 46/65 [40:00<22:59, 72.60s/it]

✅ [full] Mode3_cross_attention_train_vi_7s_mfbe_pitch | EER=19.6726% | minDCF=0.999591 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CROSS_ATTENTION
  Handcrafted Feature: PITCH_ONLY
  Num speakers: 1
  Trainable parameters: 9,771,584
======================================================================

Experiments (full):  72%|███████▏  | 47/65 [41:09<21:27, 71.52s/it]

✅ [full] Mode3_cross_attention_train_vi_7s_pitch_only | EER=11.4492% | minDCF=0.889118 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CROSS_ATTENTION
  Handcrafted Feature: MFBE_ONLY
  Num speakers: 1
  Trainable parameters: 9,801,920
======================================================================

Experiments (full):  74%|███████▍  | 48/65 [42:18<20:06, 70.97s/it]

✅ [full] Mode3_cross_attention_train_vi_full_mfbe_only | EER=4.6189% | minDCF=0.589239 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CROSS_ATTENTION
  Handcrafted Feature: MFBE_PITCH
  Num speakers: 1
  Trainable parameters: 9,802,304
======================================================================

Experiments (full):  75%|███████▌  | 49/65 [43:29<18:54, 70.92s/it]

✅ [full] Mode3_cross_attention_train_vi_full_mfbe_pitch | EER=4.2537% | minDCF=0.578464 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CROSS_ATTENTION
  Handcrafted Feature: PITCH_ONLY
  Num speakers: 1
  Trainable parameters: 9,771,584
======================================================================

Experiments (full):  77%|███████▋  | 50/65 [44:39<17:37, 70.49s/it]

✅ [full] Mode3_cross_attention_train_vi_full_pitch_only | EER=4.4499% | minDCF=0.562415 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): GATING
  Handcrafted Feature: MFBE_ONLY
  Num speakers: 1
  Trainable parameters: 9,537,728
======================================================================

Experiments (full):  78%|███████▊  | 51/65 [45:50<16:29, 70.65s/it]

✅ [full] Mode3_gating_train_raw_mfbe_only | EER=5.4372% | minDCF=0.627383 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): GATING
  Handcrafted Feature: MFBE_PITCH
  Num speakers: 1
  Trainable parameters: 9,538,112
======================================================================

Experiments (full):  80%|████████  | 52/65 [46:59<15:14, 70.38s/it]

✅ [full] Mode3_gating_train_raw_mfbe_pitch | EER=4.3755% | minDCF=0.582473 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): GATING
  Handcrafted Feature: PITCH_ONLY
  Num speakers: 1
  Trainable parameters: 9,507,392
======================================================================

Experiments (full):  82%|████████▏ | 53/65 [48:05<13:48, 69.07s/it]

✅ [full] Mode3_gating_train_raw_pitch_only | EER=8.3046% | minDCF=0.697622 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): GATING
  Handcrafted Feature: MFBE_ONLY
  Num speakers: 1
  Trainable parameters: 9,537,728
======================================================================

Experiments (full):  83%|████████▎ | 54/65 [49:14<12:38, 68.94s/it]

✅ [full] Mode3_gating_train_vi_3s_mfbe_only | EER=18.9355% | minDCF=1.000000 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): GATING
  Handcrafted Feature: MFBE_PITCH
  Num speakers: 1
  Trainable parameters: 9,538,112
======================================================================

Experiments (full):  85%|████████▍ | 55/65 [50:24<11:33, 69.34s/it]

✅ [full] Mode3_gating_train_vi_3s_mfbe_pitch | EER=27.1388% | minDCF=0.997956 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): GATING
  Handcrafted Feature: PITCH_ONLY
  Num speakers: 1
  Trainable parameters: 9,507,392
======================================================================

Experiments (full):  86%|████████▌ | 56/65 [51:34<10:26, 69.56s/it]

✅ [full] Mode3_gating_train_vi_3s_pitch_only | EER=4.5445% | minDCF=0.586561 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): GATING
  Handcrafted Feature: MFBE_ONLY
  Num speakers: 1
  Trainable parameters: 9,537,728
======================================================================

Experiments (full):  88%|████████▊ | 57/65 [52:43<09:14, 69.36s/it]

✅ [full] Mode3_gating_train_vi_5s_mfbe_only | EER=36.0520% | minDCF=1.000000 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): GATING
  Handcrafted Feature: MFBE_PITCH
  Num speakers: 1
  Trainable parameters: 9,538,112
======================================================================

Experiments (full):  89%|████████▉ | 58/65 [53:52<08:03, 69.01s/it]

✅ [full] Mode3_gating_train_vi_5s_mfbe_pitch | EER=26.5301% | minDCF=1.000000 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): GATING
  Handcrafted Feature: PITCH_ONLY
  Num speakers: 1
  Trainable parameters: 9,507,392
======================================================================

Experiments (full):  91%|█████████ | 59/65 [54:58<06:50, 68.38s/it]

✅ [full] Mode3_gating_train_vi_5s_pitch_only | EER=5.8903% | minDCF=0.674239 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): GATING
  Handcrafted Feature: MFBE_ONLY
  Num speakers: 1
  Trainable parameters: 9,537,728
======================================================================

Experiments (full):  92%|█████████▏| 60/65 [56:11<05:48, 69.68s/it]

✅ [full] Mode3_gating_train_vi_7s_mfbe_only | EER=40.9550% | minDCF=1.000000 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): GATING
  Handcrafted Feature: MFBE_PITCH
  Num speakers: 1
  Trainable parameters: 9,538,112
======================================================================

Experiments (full):  94%|█████████▍| 61/65 [57:19<04:36, 69.24s/it]

✅ [full] Mode3_gating_train_vi_7s_mfbe_pitch | EER=42.5238% | minDCF=1.000000 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): GATING
  Handcrafted Feature: PITCH_ONLY
  Num speakers: 1
  Trainable parameters: 9,507,392
======================================================================

Experiments (full):  95%|█████████▌| 62/65 [58:27<03:25, 68.61s/it]

✅ [full] Mode3_gating_train_vi_7s_pitch_only | EER=12.3420% | minDCF=0.900355 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): GATING
  Handcrafted Feature: MFBE_ONLY
  Num speakers: 1
  Trainable parameters: 9,537,728
======================================================================

Experiments (full):  97%|█████████▋| 63/65 [59:35<02:17, 68.54s/it]

✅ [full] Mode3_gating_train_vi_full_mfbe_only | EER=6.2149% | minDCF=0.783441 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): GATING
  Handcrafted Feature: MFBE_PITCH
  Num speakers: 1
  Trainable parameters: 9,538,112
======================================================================

Experiments (full):  98%|█████████▊| 64/65 [1:00:43<01:08, 68.48s/it]

✅ [full] Mode3_gating_train_vi_full_mfbe_pitch | EER=6.3705% | minDCF=0.678016 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): GATING
  Handcrafted Feature: PITCH_ONLY
  Num speakers: 1
  Trainable parameters: 9,507,392
======================================================================

Experiments (full): 100%|██████████| 65/65 [1:01:50<00:00, 57.08s/it]

✅ [full] Mode3_gating_train_vi_full_pitch_only | EER=4.6256% | minDCF=0.566663 | pairs_used=9895 | missing=0

✅ TOP RESULTS [full] (status=ok)

,test_set,experiment,mode,feature_mode,fusion_method,checkpoint,status,eer_percent,mindcf,pairs_used,pairs_missing
33,full,Mode3_concat_train_vi_full_mfbe_pitch,3,mfbe_pitch,concat,best_model.pth,ok,3.9291,0.594915,9895,0
0,full,Mode1_FBank_train_raw,1,N/A,N/A,best_model.pth,ok,4.1253,0.540997,9895,0
40,full,Mode3_cross_attention_train_vi_3s_pitch_only,3,pitch_only,cross_attention,best_model.pth,ok,4.1320,0.558424,9895,0
35,full,Mode3_cross_attention_train_raw_mfbe_only,3,mfbe_only,cross_attention,best_model.pth,ok,4.1793,0.586109,9895,0
38,full,Mode3_cross_attention_train_vi_3s_mfbe_only,3,mfbe_only,cross_attention,best_model.pth,ok,4.2199,0.584847,9895,0
41,full,Mode3_cross_attention_train_vi_5s_mfbe_only,3,mfbe_only,cross_attention,best_model.pth,ok,4.2470,0.572155,9895,0
39,full,Mode3_cross_attention_train_vi_3s_mfbe_pitch,3,mfbe_pitch,cross_attention,best_model.pth,ok,4.2537,0.568602,9895,0
48,full,Mode3_cross_attention_train_vi_full_mfbe_pitch,3,mfbe_pitch,cross_attention,best_model.pth,ok,4.2537,0.578464,9895,0
20,full,Mode3_concat_train_raw_mfbe_only,3,mfbe_only,concat,best_model.pth,ok,4.3349,0.570964,9895,0
1,full,Mode1_FBank_train_vi_3s,1,N/A,N/A,best_model.pth,ok,4.3687,0.629391,9895,0
42,full,Mode3_cross_attention_train_vi_5s_mfbe_pitch,3,mfbe_pitch,cross_attention,best_model.pth,ok,4.3755,0.581843,9895,0
51,full,Mode3_gating_train_raw_mfbe_pitch,3,mfbe_pitch,gating,best_model.pth,ok,4.3755,0.582473,9895,0
4,full,Mode1_FBank_train_vi_full,1,N/A,N/A,best_model.pth,ok,4.4160,0.604177,9895,0
49,full,Mode3_cross_attention_train_vi_full_pitch_only,3,pitch_only,cross_attention,best_model.pth,ok,4.4499,0.562415,9895,0
22,full,Mode3_concat_train_raw_pitch_only,3,pitch_only,concat,best_model.pth,ok,4.4499,0.650571,9895,0
55,full,Mode3_gating_train_vi_3s_pitch_only,3,pitch_only,gating,best_model.pth,ok,4.5445,0.586561,9895,0
2,full,Mode1_FBank_train_vi_5s,1,N/A,N/A,best_model.pth,ok,4.5716,0.574253,9895,0
43,full,Mode3_cross_attention_train_vi_5s_pitch_only,3,pitch_only,cross_attention,best_model.pth,ok,4.6122,0.590252,9895,0
47,full,Mode3_cross_attention_train_vi_full_mfbe_only,3,mfbe_only,cross_attention,best_model.pth,ok,4.6189,0.589239,9895,0
64,full,Mode3_gating_train_vi_full_pitch_only,3,pitch_only,gating,best_model.pth,ok,4.6256,0.566663,9895,0

💾 [full] Đã lưu bảng tổng hợp: outputs\experiments\inference_test_o_summary_full.csv

====================================================================================================
ĐANG CHẠY TEST SET: 3s
====================================================================================================
✅ [3s] Loaded CSV pairs: 9895 rows from D:\test_o\list_gt\test_list_gt_3s.csv

Experiments (3s):   0%|          | 0/65 [00:00<?, ?it/s]

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 1 (1=Main, 2=Handcrafted, 3=Fusion)
  Num speakers: 1
  Trainable parameters: 7,962,176
======================================================================

Experiments (3s):   2%|▏         | 1/65 [00:32<34:31, 32.37s/it]

✅ [3s] Mode1_FBank_train_raw | EER=4.2199% | minDCF=0.696280 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 1 (1=Main, 2=Handcrafted, 3=Fusion)
  Num speakers: 1
  Trainable parameters: 7,962,176
======================================================================

Experiments (3s):   3%|▎         | 2/65 [01:02<32:37, 31.07s/it]

✅ [3s] Mode1_FBank_train_vi_3s | EER=4.4905% | minDCF=0.703157 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 1 (1=Main, 2=Handcrafted, 3=Fusion)
  Num speakers: 1
  Trainable parameters: 7,962,176
======================================================================

Experiments (3s):   5%|▍         | 3/65 [01:32<31:46, 30.75s/it]

✅ [3s] Mode1_FBank_train_vi_5s | EER=5.1126% | minDCF=0.629311 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 1 (1=Main, 2=Handcrafted, 3=Fusion)
  Num speakers: 1
  Trainable parameters: 7,962,176
======================================================================

Experiments (3s):   6%|▌         | 4/65 [02:02<31:00, 30.49s/it]

✅ [3s] Mode1_FBank_train_vi_7s | EER=13.6945% | minDCF=0.821620 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 1 (1=Main, 2=Handcrafted, 3=Fusion)
  Num speakers: 1
  Trainable parameters: 7,962,176
======================================================================

Experiments (3s):   8%|▊         | 5/65 [02:32<30:15, 30.26s/it]

✅ [3s] Mode1_FBank_train_vi_full | EER=4.5445% | minDCF=0.747427 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 2 (1=Main, 2=Handcrafted, 3=Fusion)
  Handcrafted Feature: MFBE_ONLY
  Num speakers: 1
  Trainable parameters: 1,050,752
======================================================================

Experiments (3s):   9%|▉         | 6/65 [02:39<21:59, 22.36s/it]

✅ [3s] Mode2_HC_train_raw_mfbe_only | EER=13.4916% | minDCF=0.785288 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 2 (1=Main, 2=Handcrafted, 3=Fusion)
  Handcrafted Feature: MFBE_PITCH
  Num speakers: 1
  Trainable parameters: 1,051,136
======================================================================

Experiments (3s):  11%|█         | 7/65 [02:46<16:38, 17.22s/it]

✅ [3s] Mode2_HC_train_raw_mfbe_pitch | EER=13.1264% | minDCF=0.780300 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 2 (1=Main, 2=Handcrafted, 3=Fusion)
  Handcrafted Feature: PITCH_ONLY
  Num speakers: 1
  Trainable parameters: 1,020,416
======================================================================

Experiments (3s):  12%|█▏        | 8/65 [02:52<12:57, 13.64s/it]

✅ [3s] Mode2_HC_train_raw_pitch_only | EER=30.8988% | minDCF=0.914801 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 2 (1=Main, 2=Handcrafted, 3=Fusion)
  Handcrafted Feature: MFBE_ONLY
  Num speakers: 1
  Trainable parameters: 1,050,752
======================================================================

Experiments (3s):  14%|█▍        | 9/65 [02:58<10:21, 11.10s/it]

✅ [3s] Mode2_HC_train_vi_3s_mfbe_only | EER=9.8532% | minDCF=0.797278 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 2 (1=Main, 2=Handcrafted, 3=Fusion)
  Handcrafted Feature: MFBE_PITCH
  Num speakers: 1
  Trainable parameters: 1,051,136
======================================================================

Experiments (3s):  15%|█▌        | 10/65 [03:03<08:32,  9.32s/it]

✅ [3s] Mode2_HC_train_vi_3s_mfbe_pitch | EER=10.4619% | minDCF=0.778932 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 2 (1=Main, 2=Handcrafted, 3=Fusion)
  Handcrafted Feature: PITCH_ONLY
  Num speakers: 1
  Trainable parameters: 1,020,416
======================================================================

Experiments (3s):  17%|█▋        | 11/65 [03:08<07:16,  8.08s/it]

✅ [3s] Mode2_HC_train_vi_3s_pitch_only | EER=32.1363% | minDCF=0.915618 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 2 (1=Main, 2=Handcrafted, 3=Fusion)
  Handcrafted Feature: MFBE_ONLY
  Num speakers: 1
  Trainable parameters: 1,050,752
======================================================================

Experiments (3s):  18%|█▊        | 12/65 [03:14<06:27,  7.30s/it]

✅ [3s] Mode2_HC_train_vi_5s_mfbe_only | EER=10.1373% | minDCF=0.782311 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 2 (1=Main, 2=Handcrafted, 3=Fusion)
  Handcrafted Feature: MFBE_PITCH
  Num speakers: 1
  Trainable parameters: 1,051,136
======================================================================

Experiments (3s):  20%|██        | 13/65 [03:19<05:52,  6.78s/it]

✅ [3s] Mode2_HC_train_vi_5s_mfbe_pitch | EER=11.3208% | minDCF=0.711077 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 2 (1=Main, 2=Handcrafted, 3=Fusion)
  Handcrafted Feature: PITCH_ONLY
  Num speakers: 1
  Trainable parameters: 1,020,416
======================================================================

Experiments (3s):  22%|██▏       | 14/65 [03:24<05:17,  6.23s/it]

✅ [3s] Mode2_HC_train_vi_5s_pitch_only | EER=28.5791% | minDCF=0.915618 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 2 (1=Main, 2=Handcrafted, 3=Fusion)
  Handcrafted Feature: MFBE_ONLY
  Num speakers: 1
  Trainable parameters: 1,050,752
======================================================================

Experiments (3s):  23%|██▎       | 15/65 [03:30<05:01,  6.03s/it]

✅ [3s] Mode2_HC_train_vi_7s_mfbe_only | EER=23.7506% | minDCF=0.890759 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 2 (1=Main, 2=Handcrafted, 3=Fusion)
  Handcrafted Feature: MFBE_PITCH
  Num speakers: 1
  Trainable parameters: 1,051,136
======================================================================

Experiments (3s):  25%|██▍       | 16/65 [03:35<04:50,  5.94s/it]

✅ [3s] Mode2_HC_train_vi_7s_mfbe_pitch | EER=23.6627% | minDCF=0.878086 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 2 (1=Main, 2=Handcrafted, 3=Fusion)
  Handcrafted Feature: PITCH_ONLY
  Num speakers: 1
  Trainable parameters: 1,020,416
======================================================================

Experiments (3s):  26%|██▌       | 17/65 [03:40<04:29,  5.61s/it]

✅ [3s] Mode2_HC_train_vi_7s_pitch_only | EER=32.2581% | minDCF=0.916027 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 2 (1=Main, 2=Handcrafted, 3=Fusion)
  Handcrafted Feature: MFBE_ONLY
  Num speakers: 1
  Trainable parameters: 1,050,752
======================================================================

Experiments (3s):  28%|██▊       | 18/65 [03:46<04:21,  5.56s/it]

✅ [3s] Mode2_HC_train_vi_full_mfbe_only | EER=11.8483% | minDCF=0.799073 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 2 (1=Main, 2=Handcrafted, 3=Fusion)
  Handcrafted Feature: MFBE_PITCH
  Num speakers: 1
  Trainable parameters: 1,051,136
======================================================================

Experiments (3s):  29%|██▉       | 19/65 [03:52<04:19,  5.63s/it]

✅ [3s] Mode2_HC_train_vi_full_mfbe_pitch | EER=14.4316% | minDCF=0.825593 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 2 (1=Main, 2=Handcrafted, 3=Fusion)
  Handcrafted Feature: PITCH_ONLY
  Num speakers: 1
  Trainable parameters: 1,020,416
======================================================================

Experiments (3s):  31%|███       | 20/65 [03:56<04:01,  5.36s/it]

✅ [3s] Mode2_HC_train_vi_full_pitch_only | EER=33.1981% | minDCF=0.914898 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CONCAT
  Handcrafted Feature: MFBE_ONLY
  Num speakers: 1
  Trainable parameters: 9,537,728
======================================================================

Experiments (3s):  32%|███▏      | 21/65 [04:31<10:29, 14.31s/it]

✅ [3s] Mode3_concat_train_raw_mfbe_only | EER=5.5117% | minDCF=0.696609 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CONCAT
  Handcrafted Feature: MFBE_PITCH
  Num speakers: 1
  Trainable parameters: 9,538,112
======================================================================

Experiments (3s):  34%|███▍      | 22/65 [05:08<15:00, 20.94s/it]

✅ [3s] Mode3_concat_train_raw_mfbe_pitch | EER=4.5311% | minDCF=0.721949 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CONCAT
  Handcrafted Feature: PITCH_ONLY
  Num speakers: 1
  Trainable parameters: 9,507,392
======================================================================

Experiments (3s):  35%|███▌      | 23/65 [05:43<17:44, 25.35s/it]

✅ [3s] Mode3_concat_train_raw_pitch_only | EER=8.1017% | minDCF=0.816881 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CONCAT
  Handcrafted Feature: MFBE_ONLY
  Num speakers: 1
  Trainable parameters: 9,537,728
======================================================================

Experiments (3s):  37%|███▋      | 24/65 [06:21<19:43, 28.86s/it]

✅ [3s] Mode3_concat_train_vi_3s_mfbe_only | EER=5.2749% | minDCF=0.673791 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CONCAT
  Handcrafted Feature: MFBE_PITCH
  Num speakers: 1
  Trainable parameters: 9,538,112
======================================================================

Experiments (3s):  38%|███▊      | 25/65 [06:57<20:43, 31.08s/it]

✅ [3s] Mode3_concat_train_vi_3s_mfbe_pitch | EER=5.1937% | minDCF=0.707140 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CONCAT
  Handcrafted Feature: PITCH_ONLY
  Num speakers: 1
  Trainable parameters: 9,507,392
======================================================================

Experiments (3s):  40%|████      | 26/65 [07:33<21:11, 32.60s/it]

✅ [3s] Mode3_concat_train_vi_3s_pitch_only | EER=5.4711% | minDCF=0.675567 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CONCAT
  Handcrafted Feature: MFBE_ONLY
  Num speakers: 1
  Trainable parameters: 9,537,728
======================================================================

Experiments (3s):  42%|████▏     | 27/65 [08:09<21:23, 33.77s/it]

✅ [3s] Mode3_concat_train_vi_5s_mfbe_only | EER=7.3240% | minDCF=0.670892 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CONCAT
  Handcrafted Feature: MFBE_PITCH
  Num speakers: 1
  Trainable parameters: 9,538,112
======================================================================

Experiments (3s):  43%|████▎     | 28/65 [08:46<21:20, 34.60s/it]

✅ [3s] Mode3_concat_train_vi_5s_mfbe_pitch | EER=6.5463% | minDCF=0.599948 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CONCAT
  Handcrafted Feature: PITCH_ONLY
  Num speakers: 1
  Trainable parameters: 9,507,392
======================================================================

Experiments (3s):  45%|████▍     | 29/65 [09:21<20:51, 34.77s/it]

✅ [3s] Mode3_concat_train_vi_5s_pitch_only | EER=5.8024% | minDCF=0.708628 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CONCAT
  Handcrafted Feature: MFBE_ONLY
  Num speakers: 1
  Trainable parameters: 9,537,728
======================================================================

Experiments (3s):  46%|████▌     | 30/65 [09:56<20:18, 34.81s/it]

✅ [3s] Mode3_concat_train_vi_7s_mfbe_only | EER=15.0470% | minDCF=0.819098 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CONCAT
  Handcrafted Feature: MFBE_PITCH
  Num speakers: 1
  Trainable parameters: 9,538,112
======================================================================

Experiments (3s):  48%|████▊     | 31/65 [10:31<19:47, 34.93s/it]

✅ [3s] Mode3_concat_train_vi_7s_mfbe_pitch | EER=19.8755% | minDCF=0.812543 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CONCAT
  Handcrafted Feature: PITCH_ONLY
  Num speakers: 1
  Trainable parameters: 9,507,392
======================================================================

Experiments (3s):  49%|████▉     | 32/65 [11:06<19:07, 34.76s/it]

✅ [3s] Mode3_concat_train_vi_7s_pitch_only | EER=12.3960% | minDCF=0.831859 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CONCAT
  Handcrafted Feature: MFBE_ONLY
  Num speakers: 1
  Trainable parameters: 9,537,728
======================================================================

Experiments (3s):  51%|█████     | 33/65 [11:41<18:36, 34.90s/it]

✅ [3s] Mode3_concat_train_vi_full_mfbe_only | EER=5.7957% | minDCF=0.670752 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CONCAT
  Handcrafted Feature: MFBE_PITCH
  Num speakers: 1
  Trainable parameters: 9,538,112
======================================================================

Experiments (3s):  52%|█████▏    | 34/65 [12:16<18:06, 35.06s/it]

✅ [3s] Mode3_concat_train_vi_full_mfbe_pitch | EER=4.6256% | minDCF=0.748578 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CONCAT
  Handcrafted Feature: PITCH_ONLY
  Num speakers: 1
  Trainable parameters: 9,507,392
======================================================================

Experiments (3s):  54%|█████▍    | 35/65 [12:51<17:29, 34.99s/it]

✅ [3s] Mode3_concat_train_vi_full_pitch_only | EER=4.9436% | minDCF=0.723049 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CROSS_ATTENTION
  Handcrafted Feature: MFBE_ONLY
  Num speakers: 1
  Trainable parameters: 9,801,920
======================================================================

Experiments (3s):  55%|█████▌    | 36/65 [13:27<17:05, 35.38s/it]

✅ [3s] Mode3_cross_attention_train_raw_mfbe_only | EER=4.9030% | minDCF=0.732457 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CROSS_ATTENTION
  Handcrafted Feature: MFBE_PITCH
  Num speakers: 1
  Trainable parameters: 9,802,304
======================================================================

Experiments (3s):  57%|█████▋    | 37/65 [14:04<16:41, 35.76s/it]

✅ [3s] Mode3_cross_attention_train_raw_mfbe_pitch | EER=4.8963% | minDCF=0.667405 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CROSS_ATTENTION
  Handcrafted Feature: PITCH_ONLY
  Num speakers: 1
  Trainable parameters: 9,771,584
======================================================================

Experiments (3s):  58%|█████▊    | 38/65 [14:40<16:04, 35.71s/it]

✅ [3s] Mode3_cross_attention_train_raw_pitch_only | EER=6.0593% | minDCF=0.701559 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CROSS_ATTENTION
  Handcrafted Feature: MFBE_ONLY
  Num speakers: 1
  Trainable parameters: 9,801,920
======================================================================

Experiments (3s):  60%|██████    | 39/65 [15:17<15:39, 36.12s/it]

✅ [3s] Mode3_cross_attention_train_vi_3s_mfbe_only | EER=4.2604% | minDCF=0.701754 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CROSS_ATTENTION
  Handcrafted Feature: MFBE_PITCH
  Num speakers: 1
  Trainable parameters: 9,802,304
======================================================================

Experiments (3s):  62%|██████▏   | 40/65 [15:53<15:05, 36.20s/it]

✅ [3s] Mode3_cross_attention_train_vi_3s_mfbe_pitch | EER=4.2537% | minDCF=0.644485 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CROSS_ATTENTION
  Handcrafted Feature: PITCH_ONLY
  Num speakers: 1
  Trainable parameters: 9,771,584
======================================================================

Experiments (3s):  63%|██████▎   | 41/65 [16:29<14:29, 36.22s/it]

✅ [3s] Mode3_cross_attention_train_vi_3s_pitch_only | EER=5.1937% | minDCF=0.677734 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CROSS_ATTENTION
  Handcrafted Feature: MFBE_ONLY
  Num speakers: 1
  Trainable parameters: 9,801,920
======================================================================

Experiments (3s):  65%|██████▍   | 42/65 [17:05<13:51, 36.15s/it]

✅ [3s] Mode3_cross_attention_train_vi_5s_mfbe_only | EER=4.6189% | minDCF=0.680035 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CROSS_ATTENTION
  Handcrafted Feature: MFBE_PITCH
  Num speakers: 1
  Trainable parameters: 9,802,304
======================================================================

Experiments (3s):  66%|██████▌   | 43/65 [17:42<13:15, 36.15s/it]

✅ [3s] Mode3_cross_attention_train_vi_5s_mfbe_pitch | EER=5.8024% | minDCF=0.725086 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CROSS_ATTENTION
  Handcrafted Feature: PITCH_ONLY
  Num speakers: 1
  Trainable parameters: 9,771,584
======================================================================

Experiments (3s):  68%|██████▊   | 44/65 [18:17<12:37, 36.07s/it]

✅ [3s] Mode3_cross_attention_train_vi_5s_pitch_only | EER=5.2816% | minDCF=0.761978 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CROSS_ATTENTION
  Handcrafted Feature: MFBE_ONLY
  Num speakers: 1
  Trainable parameters: 9,801,920
======================================================================

Experiments (3s):  69%|██████▉   | 45/65 [18:54<12:03, 36.17s/it]

✅ [3s] Mode3_cross_attention_train_vi_7s_mfbe_only | EER=9.1228% | minDCF=0.763650 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CROSS_ATTENTION
  Handcrafted Feature: MFBE_PITCH
  Num speakers: 1
  Trainable parameters: 9,802,304
======================================================================

Experiments (3s):  71%|███████   | 46/65 [19:31<11:31, 36.41s/it]

✅ [3s] Mode3_cross_attention_train_vi_7s_mfbe_pitch | EER=16.1426% | minDCF=0.843317 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CROSS_ATTENTION
  Handcrafted Feature: PITCH_ONLY
  Num speakers: 1
  Trainable parameters: 9,771,584
======================================================================

Experiments (3s):  72%|███████▏  | 47/65 [20:06<10:49, 36.09s/it]

✅ [3s] Mode3_cross_attention_train_vi_7s_pitch_only | EER=10.7121% | minDCF=0.833368 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CROSS_ATTENTION
  Handcrafted Feature: MFBE_ONLY
  Num speakers: 1
  Trainable parameters: 9,801,920
======================================================================

Experiments (3s):  74%|███████▍  | 48/65 [20:43<10:16, 36.29s/it]

✅ [3s] Mode3_cross_attention_train_vi_full_mfbe_only | EER=5.3966% | minDCF=0.743277 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CROSS_ATTENTION
  Handcrafted Feature: MFBE_PITCH
  Num speakers: 1
  Trainable parameters: 9,802,304
======================================================================

Experiments (3s):  75%|███████▌  | 49/65 [21:19<09:39, 36.24s/it]

✅ [3s] Mode3_cross_attention_train_vi_full_mfbe_pitch | EER=4.5378% | minDCF=0.709728 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CROSS_ATTENTION
  Handcrafted Feature: PITCH_ONLY
  Num speakers: 1
  Trainable parameters: 9,771,584
======================================================================

Experiments (3s):  77%|███████▋  | 50/65 [21:55<09:02, 36.18s/it]

✅ [3s] Mode3_cross_attention_train_vi_full_pitch_only | EER=4.4160% | minDCF=0.706045 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): GATING
  Handcrafted Feature: MFBE_ONLY
  Num speakers: 1
  Trainable parameters: 9,537,728
======================================================================

Experiments (3s):  78%|███████▊  | 51/65 [22:31<08:24, 36.07s/it]

✅ [3s] Mode3_gating_train_raw_mfbe_only | EER=6.2216% | minDCF=0.790264 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): GATING
  Handcrafted Feature: MFBE_PITCH
  Num speakers: 1
  Trainable parameters: 9,538,112
======================================================================

Experiments (3s):  80%|████████  | 52/65 [23:06<07:46, 35.92s/it]

✅ [3s] Mode3_gating_train_raw_mfbe_pitch | EER=4.9030% | minDCF=0.700335 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): GATING
  Handcrafted Feature: PITCH_ONLY
  Num speakers: 1
  Trainable parameters: 9,507,392
======================================================================

Experiments (3s):  82%|████████▏ | 53/65 [23:42<07:09, 35.78s/it]

✅ [3s] Mode3_gating_train_raw_pitch_only | EER=7.0332% | minDCF=0.730687 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): GATING
  Handcrafted Feature: MFBE_ONLY
  Num speakers: 1
  Trainable parameters: 9,537,728
======================================================================

Experiments (3s):  83%|████████▎ | 54/65 [24:18<06:34, 35.86s/it]

✅ [3s] Mode3_gating_train_vi_3s_mfbe_only | EER=5.3561% | minDCF=0.691812 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): GATING
  Handcrafted Feature: MFBE_PITCH
  Num speakers: 1
  Trainable parameters: 9,538,112
======================================================================

Experiments (3s):  85%|████████▍ | 55/65 [24:54<05:58, 35.90s/it]

✅ [3s] Mode3_gating_train_vi_3s_mfbe_pitch | EER=5.7280% | minDCF=0.698885 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): GATING
  Handcrafted Feature: PITCH_ONLY
  Num speakers: 1
  Trainable parameters: 9,507,392
======================================================================

Experiments (3s):  86%|████████▌ | 56/65 [25:29<05:20, 35.67s/it]

✅ [3s] Mode3_gating_train_vi_3s_pitch_only | EER=4.6662% | minDCF=0.679489 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): GATING
  Handcrafted Feature: MFBE_ONLY
  Num speakers: 1
  Trainable parameters: 9,537,728
======================================================================

Experiments (3s):  88%|████████▊ | 57/65 [26:05<04:45, 35.66s/it]

✅ [3s] Mode3_gating_train_vi_5s_mfbe_only | EER=7.6959% | minDCF=0.738483 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): GATING
  Handcrafted Feature: MFBE_PITCH
  Num speakers: 1
  Trainable parameters: 9,538,112
======================================================================

Experiments (3s):  89%|████████▉ | 58/65 [26:41<04:10, 35.82s/it]

✅ [3s] Mode3_gating_train_vi_5s_mfbe_pitch | EER=6.9993% | minDCF=0.610017 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): GATING
  Handcrafted Feature: PITCH_ONLY
  Num speakers: 1
  Trainable parameters: 9,507,392
======================================================================

Experiments (3s):  91%|█████████ | 59/65 [27:15<03:32, 35.45s/it]

✅ [3s] Mode3_gating_train_vi_5s_pitch_only | EER=8.3723% | minDCF=0.760835 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): GATING
  Handcrafted Feature: MFBE_ONLY
  Num speakers: 1
  Trainable parameters: 9,537,728
======================================================================

Experiments (3s):  92%|█████████▏| 60/65 [27:51<02:57, 35.46s/it]

✅ [3s] Mode3_gating_train_vi_7s_mfbe_only | EER=22.8512% | minDCF=0.841334 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): GATING
  Handcrafted Feature: MFBE_PITCH
  Num speakers: 1
  Trainable parameters: 9,538,112
======================================================================

Experiments (3s):  94%|█████████▍| 61/65 [28:27<02:22, 35.58s/it]

✅ [3s] Mode3_gating_train_vi_7s_mfbe_pitch | EER=22.9323% | minDCF=0.860452 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): GATING
  Handcrafted Feature: PITCH_ONLY
  Num speakers: 1
  Trainable parameters: 9,507,392
======================================================================

Experiments (3s):  95%|█████████▌| 62/65 [29:02<01:46, 35.45s/it]

✅ [3s] Mode3_gating_train_vi_7s_pitch_only | EER=12.7612% | minDCF=0.861848 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): GATING
  Handcrafted Feature: MFBE_ONLY
  Num speakers: 1
  Trainable parameters: 9,537,728
======================================================================

Experiments (3s):  97%|█████████▋| 63/65 [29:38<01:11, 35.71s/it]

✅ [3s] Mode3_gating_train_vi_full_mfbe_only | EER=6.7897% | minDCF=0.718465 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): GATING
  Handcrafted Feature: MFBE_PITCH
  Num speakers: 1
  Trainable parameters: 9,538,112
======================================================================

Experiments (3s):  98%|█████████▊| 64/65 [30:14<00:35, 35.69s/it]

✅ [3s] Mode3_gating_train_vi_full_mfbe_pitch | EER=5.9782% | minDCF=0.791476 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): GATING
  Handcrafted Feature: PITCH_ONLY
  Num speakers: 1
  Trainable parameters: 9,507,392
======================================================================

Experiments (3s): 100%|██████████| 65/65 [30:49<00:00, 28.46s/it]

✅ [3s] Mode3_gating_train_vi_full_pitch_only | EER=4.9908% | minDCF=0.764229 | pairs_used=9895 | missing=0

✅ TOP RESULTS [3s] (status=ok)

,test_set,experiment,mode,feature_mode,fusion_method,checkpoint,status,eer_percent,mindcf,pairs_used,pairs_missing
0,3s,Mode1_FBank_train_raw,1,N/A,N/A,best_model.pth,ok,4.2199,0.696280,9895,0
39,3s,Mode3_cross_attention_train_vi_3s_mfbe_pitch,3,mfbe_pitch,cross_attention,best_model.pth,ok,4.2537,0.644485,9895,0
38,3s,Mode3_cross_attention_train_vi_3s_mfbe_only,3,mfbe_only,cross_attention,best_model.pth,ok,4.2604,0.701754,9895,0
49,3s,Mode3_cross_attention_train_vi_full_pitch_only,3,pitch_only,cross_attention,best_model.pth,ok,4.4160,0.706045,9895,0
1,3s,Mode1_FBank_train_vi_3s,1,N/A,N/A,best_model.pth,ok,4.4905,0.703157,9895,0
21,3s,Mode3_concat_train_raw_mfbe_pitch,3,mfbe_pitch,concat,best_model.pth,ok,4.5311,0.721949,9895,0
48,3s,Mode3_cross_attention_train_vi_full_mfbe_pitch,3,mfbe_pitch,cross_attention,best_model.pth,ok,4.5378,0.709728,9895,0
4,3s,Mode1_FBank_train_vi_full,1,N/A,N/A,best_model.pth,ok,4.5445,0.747427,9895,0
41,3s,Mode3_cross_attention_train_vi_5s_mfbe_only,3,mfbe_only,cross_attention,best_model.pth,ok,4.6189,0.680035,9895,0
33,3s,Mode3_concat_train_vi_full_mfbe_pitch,3,mfbe_pitch,concat,best_model.pth,ok,4.6256,0.748578,9895,0
55,3s,Mode3_gating_train_vi_3s_pitch_only,3,pitch_only,gating,best_model.pth,ok,4.6662,0.679489,9895,0
36,3s,Mode3_cross_attention_train_raw_mfbe_pitch,3,mfbe_pitch,cross_attention,best_model.pth,ok,4.8963,0.667405,9895,0
51,3s,Mode3_gating_train_raw_mfbe_pitch,3,mfbe_pitch,gating,best_model.pth,ok,4.9030,0.700335,9895,0
35,3s,Mode3_cross_attention_train_raw_mfbe_only,3,mfbe_only,cross_attention,best_model.pth,ok,4.9030,0.732457,9895,0
34,3s,Mode3_concat_train_vi_full_pitch_only,3,pitch_only,concat,best_model.pth,ok,4.9436,0.723049,9895,0
64,3s,Mode3_gating_train_vi_full_pitch_only,3,pitch_only,gating,best_model.pth,ok,4.9908,0.764229,9895,0
2,3s,Mode1_FBank_train_vi_5s,1,N/A,N/A,best_model.pth,ok,5.1126,0.629311,9895,0
40,3s,Mode3_cross_attention_train_vi_3s_pitch_only,3,pitch_only,cross_attention,best_model.pth,ok,5.1937,0.677734,9895,0
24,3s,Mode3_concat_train_vi_3s_mfbe_pitch,3,mfbe_pitch,concat,best_model.pth,ok,5.1937,0.707140,9895,0
23,3s,Mode3_concat_train_vi_3s_mfbe_only,3,mfbe_only,concat,best_model.pth,ok,5.2749,0.673791,9895,0

💾 [3s] Đã lưu bảng tổng hợp: outputs\experiments\inference_test_o_summary_3s.csv

====================================================================================================
ĐANG CHẠY TEST SET: 5s
====================================================================================================
✅ [5s] Loaded CSV pairs: 9895 rows from D:\test_o\list_gt\test_list_gt_5s.csv

Experiments (5s):   0%|          | 0/65 [00:00<?, ?it/s]

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 1 (1=Main, 2=Handcrafted, 3=Fusion)
  Num speakers: 1
  Trainable parameters: 7,962,176
======================================================================

Experiments (5s):   2%|▏         | 1/65 [00:17<18:08, 17.01s/it]

✅ [5s] Mode1_FBank_train_raw | EER=4.6595% | minDCF=0.830280 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 1 (1=Main, 2=Handcrafted, 3=Fusion)
  Num speakers: 1
  Trainable parameters: 7,962,176
======================================================================

Experiments (5s):   3%|▎         | 2/65 [00:33<17:35, 16.75s/it]

✅ [5s] Mode1_FBank_train_vi_3s | EER=5.3493% | minDCF=0.709634 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 1 (1=Main, 2=Handcrafted, 3=Fusion)
  Num speakers: 1
  Trainable parameters: 7,962,176
======================================================================

Experiments (5s):   5%|▍         | 3/65 [00:50<17:36, 17.04s/it]

✅ [5s] Mode1_FBank_train_vi_5s | EER=5.6874% | minDCF=0.739877 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 1 (1=Main, 2=Handcrafted, 3=Fusion)
  Num speakers: 1
  Trainable parameters: 7,962,176
======================================================================

Experiments (5s):   6%|▌         | 4/65 [01:08<17:25, 17.13s/it]

✅ [5s] Mode1_FBank_train_vi_7s | EER=7.8176% | minDCF=0.792070 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 1 (1=Main, 2=Handcrafted, 3=Fusion)
  Num speakers: 1
  Trainable parameters: 7,962,176
======================================================================

Experiments (5s):   8%|▊         | 5/65 [01:25<17:09, 17.15s/it]

✅ [5s] Mode1_FBank_train_vi_full | EER=5.0247% | minDCF=0.836466 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 2 (1=Main, 2=Handcrafted, 3=Fusion)
  Handcrafted Feature: MFBE_ONLY
  Num speakers: 1
  Trainable parameters: 1,050,752
======================================================================

Experiments (5s):   9%|▉         | 6/65 [01:29<12:26, 12.65s/it]

✅ [5s] Mode2_HC_train_raw_mfbe_only | EER=7.5201% | minDCF=0.864382 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 2 (1=Main, 2=Handcrafted, 3=Fusion)
  Handcrafted Feature: MFBE_PITCH
  Num speakers: 1
  Trainable parameters: 1,051,136
======================================================================

Experiments (5s):  11%|█         | 7/65 [01:33<09:29,  9.82s/it]

✅ [5s] Mode2_HC_train_raw_mfbe_pitch | EER=7.2767% | minDCF=0.783358 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 2 (1=Main, 2=Handcrafted, 3=Fusion)
  Handcrafted Feature: PITCH_ONLY
  Num speakers: 1
  Trainable parameters: 1,020,416
======================================================================

Experiments (5s):  12%|█▏        | 8/65 [01:36<07:13,  7.61s/it]

✅ [5s] Mode2_HC_train_raw_pitch_only | EER=20.6871% | minDCF=0.998462 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 2 (1=Main, 2=Handcrafted, 3=Fusion)
  Handcrafted Feature: MFBE_ONLY
  Num speakers: 1
  Trainable parameters: 1,050,752
======================================================================

Experiments (5s):  14%|█▍        | 9/65 [01:39<05:47,  6.21s/it]

✅ [5s] Mode2_HC_train_vi_3s_mfbe_only | EER=6.9115% | minDCF=0.754974 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 2 (1=Main, 2=Handcrafted, 3=Fusion)
  Handcrafted Feature: MFBE_PITCH
  Num speakers: 1
  Trainable parameters: 1,051,136
======================================================================

Experiments (5s):  15%|█▌        | 10/65 [01:42<04:46,  5.22s/it]

✅ [5s] Mode2_HC_train_vi_3s_mfbe_pitch | EER=5.9714% | minDCF=0.652340 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 2 (1=Main, 2=Handcrafted, 3=Fusion)
  Handcrafted Feature: PITCH_ONLY
  Num speakers: 1
  Trainable parameters: 1,020,416
======================================================================

Experiments (5s):  17%|█▋        | 11/65 [01:45<04:06,  4.56s/it]

✅ [5s] Mode2_HC_train_vi_3s_pitch_only | EER=27.8759% | minDCF=0.992026 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 2 (1=Main, 2=Handcrafted, 3=Fusion)
  Handcrafted Feature: MFBE_ONLY
  Num speakers: 1
  Trainable parameters: 1,050,752
======================================================================

Experiments (5s):  18%|█▊        | 12/65 [01:48<03:41,  4.18s/it]

✅ [5s] Mode2_HC_train_vi_5s_mfbe_only | EER=7.0738% | minDCF=0.817059 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 2 (1=Main, 2=Handcrafted, 3=Fusion)
  Handcrafted Feature: MFBE_PITCH
  Num speakers: 1
  Trainable parameters: 1,051,136
======================================================================

Experiments (5s):  20%|██        | 13/65 [01:51<03:18,  3.82s/it]

✅ [5s] Mode2_HC_train_vi_5s_mfbe_pitch | EER=6.6613% | minDCF=0.738708 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 2 (1=Main, 2=Handcrafted, 3=Fusion)
  Handcrafted Feature: PITCH_ONLY
  Num speakers: 1
  Trainable parameters: 1,020,416
======================================================================

Experiments (5s):  22%|██▏       | 14/65 [01:54<02:56,  3.46s/it]

✅ [5s] Mode2_HC_train_vi_5s_pitch_only | EER=30.3374% | minDCF=1.000000 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 2 (1=Main, 2=Handcrafted, 3=Fusion)
  Handcrafted Feature: MFBE_ONLY
  Num speakers: 1
  Trainable parameters: 1,050,752
======================================================================

Experiments (5s):  23%|██▎       | 15/65 [01:57<02:48,  3.36s/it]

✅ [5s] Mode2_HC_train_vi_7s_mfbe_only | EER=13.8501% | minDCF=0.923008 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 2 (1=Main, 2=Handcrafted, 3=Fusion)
  Handcrafted Feature: MFBE_PITCH
  Num speakers: 1
  Trainable parameters: 1,051,136
======================================================================

Experiments (5s):  25%|██▍       | 16/65 [02:00<02:45,  3.38s/it]

✅ [5s] Mode2_HC_train_vi_7s_mfbe_pitch | EER=14.8374% | minDCF=0.932288 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 2 (1=Main, 2=Handcrafted, 3=Fusion)
  Handcrafted Feature: PITCH_ONLY
  Num speakers: 1
  Trainable parameters: 1,020,416
======================================================================

Experiments (5s):  26%|██▌       | 17/65 [02:03<02:32,  3.18s/it]

✅ [5s] Mode2_HC_train_vi_7s_pitch_only | EER=21.5865% | minDCF=0.999591 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 2 (1=Main, 2=Handcrafted, 3=Fusion)
  Handcrafted Feature: MFBE_ONLY
  Num speakers: 1
  Trainable parameters: 1,050,752
======================================================================

Experiments (5s):  28%|██▊       | 18/65 [02:06<02:28,  3.15s/it]

✅ [5s] Mode2_HC_train_vi_full_mfbe_only | EER=7.6419% | minDCF=0.734533 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 2 (1=Main, 2=Handcrafted, 3=Fusion)
  Handcrafted Feature: MFBE_PITCH
  Num speakers: 1
  Trainable parameters: 1,051,136
======================================================================

Experiments (5s):  29%|██▉       | 19/65 [02:09<02:22,  3.11s/it]

✅ [5s] Mode2_HC_train_vi_full_mfbe_pitch | EER=7.8109% | minDCF=0.787099 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 2 (1=Main, 2=Handcrafted, 3=Fusion)
  Handcrafted Feature: PITCH_ONLY
  Num speakers: 1
  Trainable parameters: 1,020,416
======================================================================

Experiments (5s):  31%|███       | 20/65 [02:12<02:12,  2.95s/it]

✅ [5s] Mode2_HC_train_vi_full_pitch_only | EER=20.1529% | minDCF=1.000000 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CONCAT
  Handcrafted Feature: MFBE_ONLY
  Num speakers: 1
  Trainable parameters: 9,537,728
======================================================================

Experiments (5s):  32%|███▏      | 21/65 [02:31<05:41,  7.76s/it]

✅ [5s] Mode3_concat_train_raw_mfbe_only | EER=5.1464% | minDCF=0.707554 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CONCAT
  Handcrafted Feature: MFBE_PITCH
  Num speakers: 1
  Trainable parameters: 9,538,112
======================================================================

Experiments (5s):  34%|███▍      | 22/65 [02:50<08:00, 11.18s/it]

✅ [5s] Mode3_concat_train_raw_mfbe_pitch | EER=4.6122% | minDCF=0.649496 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CONCAT
  Handcrafted Feature: PITCH_ONLY
  Num speakers: 1
  Trainable parameters: 9,507,392
======================================================================

Experiments (5s):  35%|███▌      | 23/65 [03:09<09:23, 13.42s/it]

✅ [5s] Mode3_concat_train_raw_pitch_only | EER=6.3299% | minDCF=0.720018 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CONCAT
  Handcrafted Feature: MFBE_ONLY
  Num speakers: 1
  Trainable parameters: 9,537,728
======================================================================

Experiments (5s):  37%|███▋      | 24/65 [03:28<10:24, 15.24s/it]

✅ [5s] Mode3_concat_train_vi_3s_mfbe_only | EER=4.8218% | minDCF=0.734671 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CONCAT
  Handcrafted Feature: MFBE_PITCH
  Num speakers: 1
  Trainable parameters: 9,538,112
======================================================================

Experiments (5s):  38%|███▊      | 25/65 [03:47<10:54, 16.37s/it]

✅ [5s] Mode3_concat_train_vi_3s_mfbe_pitch | EER=5.8430% | minDCF=0.729858 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CONCAT
  Handcrafted Feature: PITCH_ONLY
  Num speakers: 1
  Trainable parameters: 9,507,392
======================================================================

Experiments (5s):  40%|████      | 26/65 [04:06<11:04, 17.04s/it]

✅ [5s] Mode3_concat_train_vi_3s_pitch_only | EER=4.7068% | minDCF=0.764179 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CONCAT
  Handcrafted Feature: MFBE_ONLY
  Num speakers: 1
  Trainable parameters: 9,537,728
======================================================================

Experiments (5s):  42%|████▏     | 27/65 [04:25<11:12, 17.69s/it]

✅ [5s] Mode3_concat_train_vi_5s_mfbe_only | EER=5.0314% | minDCF=0.698748 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CONCAT
  Handcrafted Feature: MFBE_PITCH
  Num speakers: 1
  Trainable parameters: 9,538,112
======================================================================

Experiments (5s):  43%|████▎     | 28/65 [04:44<11:12, 18.19s/it]

✅ [5s] Mode3_concat_train_vi_5s_mfbe_pitch | EER=6.2149% | minDCF=0.772923 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CONCAT
  Handcrafted Feature: PITCH_ONLY
  Num speakers: 1
  Trainable parameters: 9,507,392
======================================================================

Experiments (5s):  45%|████▍     | 29/65 [05:03<10:59, 18.33s/it]

✅ [5s] Mode3_concat_train_vi_5s_pitch_only | EER=5.2343% | minDCF=0.723535 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CONCAT
  Handcrafted Feature: MFBE_ONLY
  Num speakers: 1
  Trainable parameters: 9,537,728
======================================================================

Experiments (5s):  46%|████▌     | 30/65 [05:22<10:52, 18.64s/it]

✅ [5s] Mode3_concat_train_vi_7s_mfbe_only | EER=8.3451% | minDCF=0.795214 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CONCAT
  Handcrafted Feature: MFBE_PITCH
  Num speakers: 1
  Trainable parameters: 9,538,112
======================================================================

Experiments (5s):  48%|████▊     | 31/65 [05:42<10:44, 18.95s/it]

✅ [5s] Mode3_concat_train_vi_7s_mfbe_pitch | EER=9.5286% | minDCF=0.771754 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CONCAT
  Handcrafted Feature: PITCH_ONLY
  Num speakers: 1
  Trainable parameters: 9,507,392
======================================================================

Experiments (5s):  49%|████▉     | 32/65 [06:02<10:34, 19.22s/it]

✅ [5s] Mode3_concat_train_vi_7s_pitch_only | EER=7.3917% | minDCF=0.916090 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CONCAT
  Handcrafted Feature: MFBE_ONLY
  Num speakers: 1
  Trainable parameters: 9,537,728
======================================================================

Experiments (5s):  51%|█████     | 33/65 [06:22<10:22, 19.44s/it]

✅ [5s] Mode3_concat_train_vi_full_mfbe_only | EER=4.7407% | minDCF=0.592694 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CONCAT
  Handcrafted Feature: MFBE_PITCH
  Num speakers: 1
  Trainable parameters: 9,538,112
======================================================================

Experiments (5s):  52%|█████▏    | 34/65 [06:41<09:59, 19.34s/it]

✅ [5s] Mode3_concat_train_vi_full_mfbe_pitch | EER=5.5657% | minDCF=0.685141 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CONCAT
  Handcrafted Feature: PITCH_ONLY
  Num speakers: 1
  Trainable parameters: 9,507,392
======================================================================

Experiments (5s):  54%|█████▍    | 35/65 [07:01<09:43, 19.46s/it]

✅ [5s] Mode3_concat_train_vi_full_pitch_only | EER=5.8024% | minDCF=0.705799 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CROSS_ATTENTION
  Handcrafted Feature: MFBE_ONLY
  Num speakers: 1
  Trainable parameters: 9,801,920
======================================================================

Experiments (5s):  55%|█████▌    | 36/65 [07:21<09:28, 19.62s/it]

✅ [5s] Mode3_cross_attention_train_raw_mfbe_only | EER=4.9841% | minDCF=0.629489 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CROSS_ATTENTION
  Handcrafted Feature: MFBE_PITCH
  Num speakers: 1
  Trainable parameters: 9,802,304
======================================================================

Experiments (5s):  57%|█████▋    | 37/65 [07:40<09:07, 19.56s/it]

✅ [5s] Mode3_cross_attention_train_raw_mfbe_pitch | EER=4.7001% | minDCF=0.645835 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CROSS_ATTENTION
  Handcrafted Feature: PITCH_ONLY
  Num speakers: 1
  Trainable parameters: 9,771,584
======================================================================

Experiments (5s):  58%|█████▊    | 38/65 [07:59<08:46, 19.51s/it]

✅ [5s] Mode3_cross_attention_train_raw_pitch_only | EER=5.5995% | minDCF=0.793969 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CROSS_ATTENTION
  Handcrafted Feature: MFBE_ONLY
  Num speakers: 1
  Trainable parameters: 9,801,920
======================================================================

Experiments (5s):  60%|██████    | 39/65 [08:19<08:31, 19.68s/it]

✅ [5s] Mode3_cross_attention_train_vi_3s_mfbe_only | EER=4.7340% | minDCF=0.614532 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CROSS_ATTENTION
  Handcrafted Feature: MFBE_PITCH
  Num speakers: 1
  Trainable parameters: 9,802,304
======================================================================

Experiments (5s):  62%|██████▏   | 40/65 [08:40<08:15, 19.83s/it]

✅ [5s] Mode3_cross_attention_train_vi_3s_mfbe_pitch | EER=4.4160% | minDCF=0.616478 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CROSS_ATTENTION
  Handcrafted Feature: PITCH_ONLY
  Num speakers: 1
  Trainable parameters: 9,771,584
======================================================================

Experiments (5s):  63%|██████▎   | 41/65 [08:59<07:53, 19.75s/it]

✅ [5s] Mode3_cross_attention_train_vi_3s_pitch_only | EER=5.9309% | minDCF=0.736928 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CROSS_ATTENTION
  Handcrafted Feature: MFBE_ONLY
  Num speakers: 1
  Trainable parameters: 9,801,920
======================================================================

Experiments (5s):  65%|██████▍   | 42/65 [09:19<07:34, 19.76s/it]

✅ [5s] Mode3_cross_attention_train_vi_5s_mfbe_only | EER=6.0999% | minDCF=0.701924 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CROSS_ATTENTION
  Handcrafted Feature: MFBE_PITCH
  Num speakers: 1
  Trainable parameters: 9,802,304
======================================================================

Experiments (5s):  66%|██████▌   | 43/65 [09:39<07:15, 19.79s/it]

✅ [5s] Mode3_cross_attention_train_vi_5s_mfbe_pitch | EER=5.6874% | minDCF=0.779393 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CROSS_ATTENTION
  Handcrafted Feature: PITCH_ONLY
  Num speakers: 1
  Trainable parameters: 9,771,584
======================================================================

Experiments (5s):  68%|██████▊   | 44/65 [09:59<06:55, 19.80s/it]

✅ [5s] Mode3_cross_attention_train_vi_5s_pitch_only | EER=6.5057% | minDCF=0.804179 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CROSS_ATTENTION
  Handcrafted Feature: MFBE_ONLY
  Num speakers: 1
  Trainable parameters: 9,801,920
======================================================================

Experiments (5s):  69%|██████▉   | 45/65 [10:20<06:43, 20.17s/it]

✅ [5s] Mode3_cross_attention_train_vi_7s_mfbe_only | EER=5.7213% | minDCF=0.778220 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CROSS_ATTENTION
  Handcrafted Feature: MFBE_PITCH
  Num speakers: 1
  Trainable parameters: 9,802,304
======================================================================

Experiments (5s):  71%|███████   | 46/65 [10:40<06:22, 20.12s/it]

✅ [5s] Mode3_cross_attention_train_vi_7s_mfbe_pitch | EER=9.1161% | minDCF=0.923235 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CROSS_ATTENTION
  Handcrafted Feature: PITCH_ONLY
  Num speakers: 1
  Trainable parameters: 9,771,584
======================================================================

Experiments (5s):  72%|███████▏  | 47/65 [11:00<06:00, 20.05s/it]

✅ [5s] Mode3_cross_attention_train_vi_7s_pitch_only | EER=7.0738% | minDCF=0.827732 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CROSS_ATTENTION
  Handcrafted Feature: MFBE_ONLY
  Num speakers: 1
  Trainable parameters: 9,801,920
======================================================================

Experiments (5s):  74%|███████▍  | 48/65 [11:21<05:47, 20.44s/it]

✅ [5s] Mode3_cross_attention_train_vi_full_mfbe_only | EER=4.8218% | minDCF=0.726342 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CROSS_ATTENTION
  Handcrafted Feature: MFBE_PITCH
  Num speakers: 1
  Trainable parameters: 9,802,304
======================================================================

Experiments (5s):  75%|███████▌  | 49/65 [11:42<05:30, 20.65s/it]

✅ [5s] Mode3_cross_attention_train_vi_full_mfbe_pitch | EER=6.1338% | minDCF=0.755069 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CROSS_ATTENTION
  Handcrafted Feature: PITCH_ONLY
  Num speakers: 1
  Trainable parameters: 9,771,584
======================================================================

Experiments (5s):  77%|███████▋  | 50/65 [12:02<05:06, 20.46s/it]

✅ [5s] Mode3_cross_attention_train_vi_full_pitch_only | EER=4.9436% | minDCF=0.638226 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): GATING
  Handcrafted Feature: MFBE_ONLY
  Num speakers: 1
  Trainable parameters: 9,537,728
======================================================================

Experiments (5s):  78%|███████▊  | 51/65 [12:22<04:45, 20.38s/it]

✅ [5s] Mode3_gating_train_raw_mfbe_only | EER=5.5117% | minDCF=0.681935 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): GATING
  Handcrafted Feature: MFBE_PITCH
  Num speakers: 1
  Trainable parameters: 9,538,112
======================================================================

Experiments (5s):  80%|████████  | 52/65 [12:42<04:22, 20.23s/it]

✅ [5s] Mode3_gating_train_raw_mfbe_pitch | EER=4.7340% | minDCF=0.658436 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): GATING
  Handcrafted Feature: PITCH_ONLY
  Num speakers: 1
  Trainable parameters: 9,507,392
======================================================================

Experiments (5s):  82%|████████▏ | 53/65 [13:02<04:00, 20.02s/it]

✅ [5s] Mode3_gating_train_raw_pitch_only | EER=5.4778% | minDCF=0.667919 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): GATING
  Handcrafted Feature: MFBE_ONLY
  Num speakers: 1
  Trainable parameters: 9,537,728
======================================================================

Experiments (5s):  83%|████████▎ | 54/65 [13:22<03:40, 20.01s/it]

✅ [5s] Mode3_gating_train_vi_3s_mfbe_only | EER=5.9376% | minDCF=0.751722 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): GATING
  Handcrafted Feature: MFBE_PITCH
  Num speakers: 1
  Trainable parameters: 9,538,112
======================================================================

Experiments (5s):  85%|████████▍ | 55/65 [13:42<03:21, 20.16s/it]

✅ [5s] Mode3_gating_train_vi_3s_mfbe_pitch | EER=6.0932% | minDCF=0.694467 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): GATING
  Handcrafted Feature: PITCH_ONLY
  Num speakers: 1
  Trainable parameters: 9,507,392
======================================================================

Experiments (5s):  86%|████████▌ | 56/65 [14:03<03:04, 20.47s/it]

✅ [5s] Mode3_gating_train_vi_3s_pitch_only | EER=5.2276% | minDCF=0.649406 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): GATING
  Handcrafted Feature: MFBE_ONLY
  Num speakers: 1
  Trainable parameters: 9,537,728
======================================================================

Experiments (5s):  88%|████████▊ | 57/65 [14:23<02:41, 20.20s/it]

✅ [5s] Mode3_gating_train_vi_5s_mfbe_only | EER=6.4178% | minDCF=0.619561 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): GATING
  Handcrafted Feature: MFBE_PITCH
  Num speakers: 1
  Trainable parameters: 9,538,112
======================================================================

Experiments (5s):  89%|████████▉ | 58/65 [14:42<02:19, 19.96s/it]

✅ [5s] Mode3_gating_train_vi_5s_mfbe_pitch | EER=4.5445% | minDCF=0.613935 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): GATING
  Handcrafted Feature: PITCH_ONLY
  Num speakers: 1
  Trainable parameters: 9,507,392
======================================================================

Experiments (5s):  91%|█████████ | 59/65 [15:01<01:57, 19.61s/it]

✅ [5s] Mode3_gating_train_vi_5s_pitch_only | EER=5.9714% | minDCF=0.666551 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): GATING
  Handcrafted Feature: MFBE_ONLY
  Num speakers: 1
  Trainable parameters: 9,537,728
======================================================================

Experiments (5s):  92%|█████████▏| 60/65 [15:21<01:38, 19.74s/it]

✅ [5s] Mode3_gating_train_vi_7s_mfbe_only | EER=15.9058% | minDCF=0.872200 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): GATING
  Handcrafted Feature: MFBE_PITCH
  Num speakers: 1
  Trainable parameters: 9,538,112
======================================================================

Experiments (5s):  94%|█████████▍| 61/65 [15:43<01:20, 20.22s/it]

✅ [5s] Mode3_gating_train_vi_7s_mfbe_pitch | EER=15.0876% | minDCF=0.930681 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): GATING
  Handcrafted Feature: PITCH_ONLY
  Num speakers: 1
  Trainable parameters: 9,507,392
======================================================================

Experiments (5s):  95%|█████████▌| 62/65 [16:07<01:04, 21.54s/it]

✅ [5s] Mode3_gating_train_vi_7s_pitch_only | EER=10.9150% | minDCF=0.968963 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): GATING
  Handcrafted Feature: MFBE_ONLY
  Num speakers: 1
  Trainable parameters: 9,537,728
======================================================================

Experiments (5s):  97%|█████████▋| 63/65 [16:28<00:42, 21.31s/it]

✅ [5s] Mode3_gating_train_vi_full_mfbe_only | EER=5.7145% | minDCF=0.672043 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): GATING
  Handcrafted Feature: MFBE_PITCH
  Num speakers: 1
  Trainable parameters: 9,538,112
======================================================================

Experiments (5s):  98%|█████████▊| 64/65 [16:49<00:21, 21.11s/it]

✅ [5s] Mode3_gating_train_vi_full_mfbe_pitch | EER=4.6662% | minDCF=0.633143 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): GATING
  Handcrafted Feature: PITCH_ONLY
  Num speakers: 1
  Trainable parameters: 9,507,392
======================================================================

Experiments (5s): 100%|██████████| 65/65 [17:08<00:00, 15.82s/it]

✅ [5s] Mode3_gating_train_vi_full_pitch_only | EER=6.6140% | minDCF=0.745651 | pairs_used=9895 | missing=0

✅ TOP RESULTS [5s] (status=ok)

,test_set,experiment,mode,feature_mode,fusion_method,checkpoint,status,eer_percent,mindcf,pairs_used,pairs_missing
39,5s,Mode3_cross_attention_train_vi_3s_mfbe_pitch,3,mfbe_pitch,cross_attention,best_model.pth,ok,4.4160,0.616478,9895,0
57,5s,Mode3_gating_train_vi_5s_mfbe_pitch,3,mfbe_pitch,gating,best_model.pth,ok,4.5445,0.613935,9895,0
21,5s,Mode3_concat_train_raw_mfbe_pitch,3,mfbe_pitch,concat,best_model.pth,ok,4.6122,0.649496,9895,0
0,5s,Mode1_FBank_train_raw,1,N/A,N/A,best_model.pth,ok,4.6595,0.830280,9895,0
63,5s,Mode3_gating_train_vi_full_mfbe_pitch,3,mfbe_pitch,gating,best_model.pth,ok,4.6662,0.633143,9895,0
36,5s,Mode3_cross_attention_train_raw_mfbe_pitch,3,mfbe_pitch,cross_attention,best_model.pth,ok,4.7001,0.645835,9895,0
25,5s,Mode3_concat_train_vi_3s_pitch_only,3,pitch_only,concat,best_model.pth,ok,4.7068,0.764179,9895,0
38,5s,Mode3_cross_attention_train_vi_3s_mfbe_only,3,mfbe_only,cross_attention,best_model.pth,ok,4.7340,0.614532,9895,0
51,5s,Mode3_gating_train_raw_mfbe_pitch,3,mfbe_pitch,gating,best_model.pth,ok,4.7340,0.658436,9895,0
32,5s,Mode3_concat_train_vi_full_mfbe_only,3,mfbe_only,concat,best_model.pth,ok,4.7407,0.592694,9895,0
47,5s,Mode3_cross_attention_train_vi_full_mfbe_only,3,mfbe_only,cross_attention,best_model.pth,ok,4.8218,0.726342,9895,0
23,5s,Mode3_concat_train_vi_3s_mfbe_only,3,mfbe_only,concat,best_model.pth,ok,4.8218,0.734671,9895,0
49,5s,Mode3_cross_attention_train_vi_full_pitch_only,3,pitch_only,cross_attention,best_model.pth,ok,4.9436,0.638226,9895,0
35,5s,Mode3_cross_attention_train_raw_mfbe_only,3,mfbe_only,cross_attention,best_model.pth,ok,4.9841,0.629489,9895,0
4,5s,Mode1_FBank_train_vi_full,1,N/A,N/A,best_model.pth,ok,5.0247,0.836466,9895,0
26,5s,Mode3_concat_train_vi_5s_mfbe_only,3,mfbe_only,concat,best_model.pth,ok,5.0314,0.698748,9895,0
20,5s,Mode3_concat_train_raw_mfbe_only,3,mfbe_only,concat,best_model.pth,ok,5.1464,0.707554,9895,0
55,5s,Mode3_gating_train_vi_3s_pitch_only,3,pitch_only,gating,best_model.pth,ok,5.2276,0.649406,9895,0
28,5s,Mode3_concat_train_vi_5s_pitch_only,3,pitch_only,concat,best_model.pth,ok,5.2343,0.723535,9895,0
1,5s,Mode1_FBank_train_vi_3s,1,N/A,N/A,best_model.pth,ok,5.3493,0.709634,9895,0

💾 [5s] Đã lưu bảng tổng hợp: outputs\experiments\inference_test_o_summary_5s.csv

====================================================================================================
ĐANG CHẠY TEST SET: 7s
====================================================================================================
✅ [7s] Loaded CSV pairs: 9895 rows from D:\test_o\list_gt\test_list_gt_7s.csv

Experiments (7s):   0%|          | 0/65 [00:00<?, ?it/s]

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 1 (1=Main, 2=Handcrafted, 3=Fusion)
  Num speakers: 1
  Trainable parameters: 7,962,176
======================================================================

Experiments (7s):   2%|▏         | 1/65 [00:08<09:00,  8.45s/it]

✅ [7s] Mode1_FBank_train_raw | EER=3.5505% | minDCF=0.608718 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 1 (1=Main, 2=Handcrafted, 3=Fusion)
  Num speakers: 1
  Trainable parameters: 7,962,176
======================================================================

Experiments (7s):   3%|▎         | 2/65 [00:16<08:39,  8.25s/it]

✅ [7s] Mode1_FBank_train_vi_3s | EER=3.5505% | minDCF=0.596587 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 1 (1=Main, 2=Handcrafted, 3=Fusion)
  Num speakers: 1
  Trainable parameters: 7,962,176
======================================================================

Experiments (7s):   5%|▍         | 3/65 [00:25<08:38,  8.36s/it]

✅ [7s] Mode1_FBank_train_vi_5s | EER=3.6856% | minDCF=0.621323 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 1 (1=Main, 2=Handcrafted, 3=Fusion)
  Num speakers: 1
  Trainable parameters: 7,962,176
======================================================================

Experiments (7s):   6%|▌         | 4/65 [00:34<08:54,  8.76s/it]

✅ [7s] Mode1_FBank_train_vi_7s | EER=6.0120% | minDCF=0.780543 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 1 (1=Main, 2=Handcrafted, 3=Fusion)
  Num speakers: 1
  Trainable parameters: 7,962,176
======================================================================

Experiments (7s):   8%|▊         | 5/65 [00:43<09:01,  9.02s/it]

✅ [7s] Mode1_FBank_train_vi_full | EER=3.5978% | minDCF=0.642188 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 2 (1=Main, 2=Handcrafted, 3=Fusion)
  Handcrafted Feature: MFBE_ONLY
  Num speakers: 1
  Trainable parameters: 1,050,752
======================================================================

Experiments (7s):   9%|▉         | 6/65 [00:45<06:28,  6.59s/it]

✅ [7s] Mode2_HC_train_raw_mfbe_only | EER=6.9520% | minDCF=0.655871 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 2 (1=Main, 2=Handcrafted, 3=Fusion)
  Handcrafted Feature: MFBE_PITCH
  Num speakers: 1
  Trainable parameters: 1,051,136
======================================================================

Experiments (7s):  11%|█         | 7/65 [00:47<04:52,  5.04s/it]

✅ [7s] Mode2_HC_train_raw_mfbe_pitch | EER=6.5801% | minDCF=0.687358 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 2 (1=Main, 2=Handcrafted, 3=Fusion)
  Handcrafted Feature: PITCH_ONLY
  Num speakers: 1
  Trainable parameters: 1,020,416
======================================================================

Experiments (7s):  12%|█▏        | 8/65 [00:49<03:43,  3.91s/it]

✅ [7s] Mode2_HC_train_raw_pitch_only | EER=20.1529% | minDCF=0.950959 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 2 (1=Main, 2=Handcrafted, 3=Fusion)
  Handcrafted Feature: MFBE_ONLY
  Num speakers: 1
  Trainable parameters: 1,050,752
======================================================================

Experiments (7s):  14%|█▍        | 9/65 [00:50<02:57,  3.18s/it]

✅ [7s] Mode2_HC_train_vi_3s_mfbe_only | EER=6.2082% | minDCF=0.684663 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 2 (1=Main, 2=Handcrafted, 3=Fusion)
  Handcrafted Feature: MFBE_PITCH
  Num speakers: 1
  Trainable parameters: 1,051,136
======================================================================

Experiments (7s):  15%|█▌        | 10/65 [00:52<02:26,  2.66s/it]

✅ [7s] Mode2_HC_train_vi_3s_mfbe_pitch | EER=4.9503% | minDCF=0.602889 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 2 (1=Main, 2=Handcrafted, 3=Fusion)
  Handcrafted Feature: PITCH_ONLY
  Num speakers: 1
  Trainable parameters: 1,020,416
======================================================================

Experiments (7s):  17%|█▋        | 11/65 [00:53<02:05,  2.32s/it]

✅ [7s] Mode2_HC_train_vi_3s_pitch_only | EER=18.6920% | minDCF=0.944729 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 2 (1=Main, 2=Handcrafted, 3=Fusion)
  Handcrafted Feature: MFBE_ONLY
  Num speakers: 1
  Trainable parameters: 1,050,752
======================================================================

Experiments (7s):  18%|█▊        | 12/65 [00:55<01:54,  2.15s/it]

✅ [7s] Mode2_HC_train_vi_5s_mfbe_only | EER=6.8370% | minDCF=0.693071 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 2 (1=Main, 2=Handcrafted, 3=Fusion)
  Handcrafted Feature: MFBE_PITCH
  Num speakers: 1
  Trainable parameters: 1,051,136
======================================================================

Experiments (7s):  20%|██        | 13/65 [00:57<01:41,  1.96s/it]

✅ [7s] Mode2_HC_train_vi_5s_mfbe_pitch | EER=6.4245% | minDCF=0.641721 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 2 (1=Main, 2=Handcrafted, 3=Fusion)
  Handcrafted Feature: PITCH_ONLY
  Num speakers: 1
  Trainable parameters: 1,020,416
======================================================================

Experiments (7s):  22%|██▏       | 14/65 [00:58<01:29,  1.76s/it]

✅ [7s] Mode2_HC_train_vi_5s_pitch_only | EER=18.1105% | minDCF=0.921017 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 2 (1=Main, 2=Handcrafted, 3=Fusion)
  Handcrafted Feature: MFBE_ONLY
  Num speakers: 1
  Trainable parameters: 1,050,752
======================================================================

Experiments (7s):  23%|██▎       | 15/65 [00:59<01:24,  1.68s/it]

✅ [7s] Mode2_HC_train_vi_7s_mfbe_only | EER=10.3875% | minDCF=0.916173 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 2 (1=Main, 2=Handcrafted, 3=Fusion)
  Handcrafted Feature: MFBE_PITCH
  Num speakers: 1
  Trainable parameters: 1,051,136
======================================================================

Experiments (7s):  25%|██▍       | 16/65 [01:01<01:19,  1.62s/it]

✅ [7s] Mode2_HC_train_vi_7s_mfbe_pitch | EER=11.4492% | minDCF=0.860420 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 2 (1=Main, 2=Handcrafted, 3=Fusion)
  Handcrafted Feature: PITCH_ONLY
  Num speakers: 1
  Trainable parameters: 1,020,416
======================================================================

Experiments (7s):  26%|██▌       | 17/65 [01:02<01:13,  1.53s/it]

✅ [7s] Mode2_HC_train_vi_7s_pitch_only | EER=18.3540% | minDCF=0.947561 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 2 (1=Main, 2=Handcrafted, 3=Fusion)
  Handcrafted Feature: MFBE_ONLY
  Num speakers: 1
  Trainable parameters: 1,050,752
======================================================================

Experiments (7s):  28%|██▊       | 18/65 [01:04<01:12,  1.55s/it]

✅ [7s] Mode2_HC_train_vi_full_mfbe_only | EER=7.1616% | minDCF=0.716909 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 2 (1=Main, 2=Handcrafted, 3=Fusion)
  Handcrafted Feature: MFBE_PITCH
  Num speakers: 1
  Trainable parameters: 1,051,136
======================================================================

Experiments (7s):  29%|██▉       | 19/65 [01:05<01:11,  1.55s/it]

✅ [7s] Mode2_HC_train_vi_full_mfbe_pitch | EER=6.5734% | minDCF=0.655017 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 2 (1=Main, 2=Handcrafted, 3=Fusion)
  Handcrafted Feature: PITCH_ONLY
  Num speakers: 1
  Trainable parameters: 1,020,416
======================================================================

Experiments (7s):  31%|███       | 20/65 [01:07<01:07,  1.50s/it]

✅ [7s] Mode2_HC_train_vi_full_pitch_only | EER=19.0099% | minDCF=0.884479 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CONCAT
  Handcrafted Feature: MFBE_ONLY
  Num speakers: 1
  Trainable parameters: 9,537,728
======================================================================

Experiments (7s):  32%|███▏      | 21/65 [01:17<02:57,  4.03s/it]

✅ [7s] Mode3_concat_train_raw_mfbe_only | EER=3.7601% | minDCF=0.638342 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CONCAT
  Handcrafted Feature: MFBE_PITCH
  Num speakers: 1
  Trainable parameters: 9,538,112
======================================================================

Experiments (7s):  34%|███▍      | 22/65 [01:26<04:02,  5.63s/it]

✅ [7s] Mode3_concat_train_raw_mfbe_pitch | EER=3.6789% | minDCF=0.603074 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CONCAT
  Handcrafted Feature: PITCH_ONLY
  Num speakers: 1
  Trainable parameters: 9,507,392
======================================================================

Experiments (7s):  35%|███▌      | 23/65 [01:35<04:40,  6.68s/it]

✅ [7s] Mode3_concat_train_raw_pitch_only | EER=4.1726% | minDCF=0.706979 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CONCAT
  Handcrafted Feature: MFBE_ONLY
  Num speakers: 1
  Trainable parameters: 9,537,728
======================================================================

Experiments (7s):  37%|███▋      | 24/65 [01:45<05:09,  7.55s/it]

✅ [7s] Mode3_concat_train_vi_3s_mfbe_only | EER=3.7195% | minDCF=0.608736 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CONCAT
  Handcrafted Feature: MFBE_PITCH
  Num speakers: 1
  Trainable parameters: 9,538,112
======================================================================

Experiments (7s):  38%|███▊      | 25/65 [01:54<05:23,  8.09s/it]

✅ [7s] Mode3_concat_train_vi_3s_mfbe_pitch | EER=3.9157% | minDCF=0.643772 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CONCAT
  Handcrafted Feature: PITCH_ONLY
  Num speakers: 1
  Trainable parameters: 9,507,392
======================================================================

Experiments (7s):  40%|████      | 26/65 [02:03<05:31,  8.49s/it]

✅ [7s] Mode3_concat_train_vi_3s_pitch_only | EER=3.5166% | minDCF=0.586268 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CONCAT
  Handcrafted Feature: MFBE_ONLY
  Num speakers: 1
  Trainable parameters: 9,537,728
======================================================================

Experiments (7s):  42%|████▏     | 27/65 [02:13<05:35,  8.83s/it]

✅ [7s] Mode3_concat_train_vi_5s_mfbe_only | EER=4.5378% | minDCF=0.574130 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CONCAT
  Handcrafted Feature: MFBE_PITCH
  Num speakers: 1
  Trainable parameters: 9,538,112
======================================================================

Experiments (7s):  43%|████▎     | 28/65 [02:23<05:34,  9.04s/it]

✅ [7s] Mode3_concat_train_vi_5s_mfbe_pitch | EER=4.1253% | minDCF=0.599449 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CONCAT
  Handcrafted Feature: PITCH_ONLY
  Num speakers: 1
  Trainable parameters: 9,507,392
======================================================================

Experiments (7s):  45%|████▍     | 29/65 [02:32<05:27,  9.10s/it]

✅ [7s] Mode3_concat_train_vi_5s_pitch_only | EER=3.8006% | minDCF=0.621526 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CONCAT
  Handcrafted Feature: MFBE_ONLY
  Num speakers: 1
  Trainable parameters: 9,537,728
======================================================================

Experiments (7s):  46%|████▌     | 30/65 [02:41<05:23,  9.24s/it]

✅ [7s] Mode3_concat_train_vi_7s_mfbe_only | EER=8.6292% | minDCF=0.741031 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CONCAT
  Handcrafted Feature: MFBE_PITCH
  Num speakers: 1
  Trainable parameters: 9,538,112
======================================================================

Experiments (7s):  48%|████▊     | 31/65 [02:51<05:15,  9.28s/it]

✅ [7s] Mode3_concat_train_vi_7s_mfbe_pitch | EER=8.2167% | minDCF=0.708165 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CONCAT
  Handcrafted Feature: PITCH_ONLY
  Num speakers: 1
  Trainable parameters: 9,507,392
======================================================================

Experiments (7s):  49%|████▉     | 32/65 [03:00<05:04,  9.24s/it]

✅ [7s] Mode3_concat_train_vi_7s_pitch_only | EER=5.8836% | minDCF=0.706598 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CONCAT
  Handcrafted Feature: MFBE_ONLY
  Num speakers: 1
  Trainable parameters: 9,537,728
======================================================================

Experiments (7s):  51%|█████     | 33/65 [03:09<04:57,  9.28s/it]

✅ [7s] Mode3_concat_train_vi_full_mfbe_only | EER=3.5572% | minDCF=0.595983 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CONCAT
  Handcrafted Feature: MFBE_PITCH
  Num speakers: 1
  Trainable parameters: 9,538,112
======================================================================

Experiments (7s):  52%|█████▏    | 34/65 [03:19<04:49,  9.32s/it]

✅ [7s] Mode3_concat_train_vi_full_mfbe_pitch | EER=3.8818% | minDCF=0.666095 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CONCAT
  Handcrafted Feature: PITCH_ONLY
  Num speakers: 1
  Trainable parameters: 9,507,392
======================================================================

Experiments (7s):  54%|█████▍    | 35/65 [03:28<04:38,  9.29s/it]

✅ [7s] Mode3_concat_train_vi_full_pitch_only | EER=3.6045% | minDCF=0.639673 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CROSS_ATTENTION
  Handcrafted Feature: MFBE_ONLY
  Num speakers: 1
  Trainable parameters: 9,801,920
======================================================================

Experiments (7s):  55%|█████▌    | 36/65 [03:38<04:34,  9.46s/it]

✅ [7s] Mode3_cross_attention_train_raw_mfbe_only | EER=3.7668% | minDCF=0.640882 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CROSS_ATTENTION
  Handcrafted Feature: MFBE_PITCH
  Num speakers: 1
  Trainable parameters: 9,802,304
======================================================================

Experiments (7s):  57%|█████▋    | 37/65 [03:48<04:27,  9.55s/it]

✅ [7s] Mode3_cross_attention_train_raw_mfbe_pitch | EER=3.5233% | minDCF=0.609492 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CROSS_ATTENTION
  Handcrafted Feature: PITCH_ONLY
  Num speakers: 1
  Trainable parameters: 9,771,584
======================================================================

Experiments (7s):  58%|█████▊    | 38/65 [03:57<04:17,  9.54s/it]

✅ [7s] Mode3_cross_attention_train_raw_pitch_only | EER=3.8006% | minDCF=0.672933 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CROSS_ATTENTION
  Handcrafted Feature: MFBE_ONLY
  Num speakers: 1
  Trainable parameters: 9,801,920
======================================================================

Experiments (7s):  60%|██████    | 39/65 [04:07<04:11,  9.67s/it]

✅ [7s] Mode3_cross_attention_train_vi_3s_mfbe_only | EER=3.3949% | minDCF=0.560237 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CROSS_ATTENTION
  Handcrafted Feature: MFBE_PITCH
  Num speakers: 1
  Trainable parameters: 9,802,304
======================================================================

Experiments (7s):  62%|██████▏   | 40/65 [04:17<04:02,  9.71s/it]

✅ [7s] Mode3_cross_attention_train_vi_3s_mfbe_pitch | EER=3.3610% | minDCF=0.563801 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CROSS_ATTENTION
  Handcrafted Feature: PITCH_ONLY
  Num speakers: 1
  Trainable parameters: 9,771,584
======================================================================

Experiments (7s):  63%|██████▎   | 41/65 [04:26<03:52,  9.67s/it]

✅ [7s] Mode3_cross_attention_train_vi_3s_pitch_only | EER=3.6856% | minDCF=0.623117 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CROSS_ATTENTION
  Handcrafted Feature: MFBE_ONLY
  Num speakers: 1
  Trainable parameters: 9,801,920
======================================================================

Experiments (7s):  65%|██████▍   | 42/65 [04:36<03:44,  9.75s/it]

✅ [7s] Mode3_cross_attention_train_vi_5s_mfbe_only | EER=3.7668% | minDCF=0.624174 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CROSS_ATTENTION
  Handcrafted Feature: MFBE_PITCH
  Num speakers: 1
  Trainable parameters: 9,802,304
======================================================================

Experiments (7s):  66%|██████▌   | 43/65 [04:46<03:35,  9.80s/it]

✅ [7s] Mode3_cross_attention_train_vi_5s_mfbe_pitch | EER=3.8479% | minDCF=0.657723 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CROSS_ATTENTION
  Handcrafted Feature: PITCH_ONLY
  Num speakers: 1
  Trainable parameters: 9,771,584
======================================================================

Experiments (7s):  68%|██████▊   | 44/65 [04:56<03:24,  9.72s/it]

✅ [7s] Mode3_cross_attention_train_vi_5s_pitch_only | EER=4.0914% | minDCF=0.663244 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CROSS_ATTENTION
  Handcrafted Feature: MFBE_ONLY
  Num speakers: 1
  Trainable parameters: 9,801,920
======================================================================

Experiments (7s):  69%|██████▉   | 45/65 [05:06<03:15,  9.78s/it]

✅ [7s] Mode3_cross_attention_train_vi_7s_mfbe_only | EER=4.7880% | minDCF=0.670665 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CROSS_ATTENTION
  Handcrafted Feature: MFBE_PITCH
  Num speakers: 1
  Trainable parameters: 9,802,304
======================================================================

Experiments (7s):  71%|███████   | 46/65 [05:16<03:05,  9.79s/it]

✅ [7s] Mode3_cross_attention_train_vi_7s_mfbe_pitch | EER=7.0738% | minDCF=0.756921 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CROSS_ATTENTION
  Handcrafted Feature: PITCH_ONLY
  Num speakers: 1
  Trainable parameters: 9,771,584
======================================================================

Experiments (7s):  72%|███████▏  | 47/65 [05:25<02:55,  9.74s/it]

✅ [7s] Mode3_cross_attention_train_vi_7s_pitch_only | EER=5.1126% | minDCF=0.687018 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CROSS_ATTENTION
  Handcrafted Feature: MFBE_ONLY
  Num speakers: 1
  Trainable parameters: 9,801,920
======================================================================

Experiments (7s):  74%|███████▍  | 48/65 [05:35<02:45,  9.75s/it]

✅ [7s] Mode3_cross_attention_train_vi_full_mfbe_only | EER=3.6450% | minDCF=0.619952 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CROSS_ATTENTION
  Handcrafted Feature: MFBE_PITCH
  Num speakers: 1
  Trainable parameters: 9,802,304
======================================================================

Experiments (7s):  75%|███████▌  | 49/65 [05:45<02:35,  9.72s/it]

✅ [7s] Mode3_cross_attention_train_vi_full_mfbe_pitch | EER=3.8479% | minDCF=0.654214 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CROSS_ATTENTION
  Handcrafted Feature: PITCH_ONLY
  Num speakers: 1
  Trainable parameters: 9,771,584
======================================================================

Experiments (7s):  77%|███████▋  | 50/65 [05:54<02:25,  9.67s/it]

✅ [7s] Mode3_cross_attention_train_vi_full_pitch_only | EER=3.5978% | minDCF=0.603653 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): GATING
  Handcrafted Feature: MFBE_ONLY
  Num speakers: 1
  Trainable parameters: 9,537,728
======================================================================

Experiments (7s):  78%|███████▊  | 51/65 [06:04<02:14,  9.63s/it]

✅ [7s] Mode3_gating_train_raw_mfbe_only | EER=3.6450% | minDCF=0.651982 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): GATING
  Handcrafted Feature: MFBE_PITCH
  Num speakers: 1
  Trainable parameters: 9,538,112
======================================================================

Experiments (7s):  80%|████████  | 52/65 [06:13<02:05,  9.67s/it]

✅ [7s] Mode3_gating_train_raw_mfbe_pitch | EER=3.6383% | minDCF=0.620921 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): GATING
  Handcrafted Feature: PITCH_ONLY
  Num speakers: 1
  Trainable parameters: 9,507,392
======================================================================

Experiments (7s):  82%|████████▏ | 53/65 [06:23<01:55,  9.59s/it]

✅ [7s] Mode3_gating_train_raw_pitch_only | EER=4.1659% | minDCF=0.686566 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): GATING
  Handcrafted Feature: MFBE_ONLY
  Num speakers: 1
  Trainable parameters: 9,537,728
======================================================================

Experiments (7s):  83%|████████▎ | 54/65 [06:32<01:45,  9.58s/it]

✅ [7s] Mode3_gating_train_vi_3s_mfbe_only | EER=4.1253% | minDCF=0.660799 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): GATING
  Handcrafted Feature: MFBE_PITCH
  Num speakers: 1
  Trainable parameters: 9,538,112
======================================================================

Experiments (7s):  85%|████████▍ | 55/65 [06:42<01:35,  9.58s/it]

✅ [7s] Mode3_gating_train_vi_3s_mfbe_pitch | EER=3.9630% | minDCF=0.688599 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): GATING
  Handcrafted Feature: PITCH_ONLY
  Num speakers: 1
  Trainable parameters: 9,507,392
======================================================================

Experiments (7s):  86%|████████▌ | 56/65 [06:51<01:25,  9.50s/it]

✅ [7s] Mode3_gating_train_vi_3s_pitch_only | EER=3.6450% | minDCF=0.621569 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): GATING
  Handcrafted Feature: MFBE_ONLY
  Num speakers: 1
  Trainable parameters: 9,537,728
======================================================================

Experiments (7s):  88%|████████▊ | 57/65 [07:01<01:16,  9.54s/it]

✅ [7s] Mode3_gating_train_vi_5s_mfbe_only | EER=5.1126% | minDCF=0.588287 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): GATING
  Handcrafted Feature: MFBE_PITCH
  Num speakers: 1
  Trainable parameters: 9,538,112
======================================================================

Experiments (7s):  89%|████████▉ | 58/65 [07:11<01:06,  9.57s/it]

✅ [7s] Mode3_gating_train_vi_5s_mfbe_pitch | EER=3.6450% | minDCF=0.573461 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): GATING
  Handcrafted Feature: PITCH_ONLY
  Num speakers: 1
  Trainable parameters: 9,507,392
======================================================================

Experiments (7s):  91%|█████████ | 59/65 [07:20<00:56,  9.46s/it]

✅ [7s] Mode3_gating_train_vi_5s_pitch_only | EER=4.5445% | minDCF=0.655857 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): GATING
  Handcrafted Feature: MFBE_ONLY
  Num speakers: 1
  Trainable parameters: 9,537,728
======================================================================

Experiments (7s):  92%|█████████▏| 60/65 [07:30<00:47,  9.56s/it]

✅ [7s] Mode3_gating_train_vi_7s_mfbe_only | EER=11.2396% | minDCF=0.871860 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): GATING
  Handcrafted Feature: MFBE_PITCH
  Num speakers: 1
  Trainable parameters: 9,538,112
======================================================================

Experiments (7s):  94%|█████████▍| 61/65 [07:39<00:38,  9.56s/it]

✅ [7s] Mode3_gating_train_vi_7s_mfbe_pitch | EER=11.1518% | minDCF=0.845543 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): GATING
  Handcrafted Feature: PITCH_ONLY
  Num speakers: 1
  Trainable parameters: 9,507,392
======================================================================

Experiments (7s):  95%|█████████▌| 62/65 [07:49<00:28,  9.54s/it]

✅ [7s] Mode3_gating_train_vi_7s_pitch_only | EER=9.1161% | minDCF=0.785557 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): GATING
  Handcrafted Feature: MFBE_ONLY
  Num speakers: 1
  Trainable parameters: 9,537,728
======================================================================

Experiments (7s):  97%|█████████▋| 63/65 [07:58<00:19,  9.56s/it]

✅ [7s] Mode3_gating_train_vi_full_mfbe_only | EER=3.9224% | minDCF=0.670274 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): GATING
  Handcrafted Feature: MFBE_PITCH
  Num speakers: 1
  Trainable parameters: 9,538,112
======================================================================

Experiments (7s):  98%|█████████▊| 64/65 [08:08<00:09,  9.59s/it]

✅ [7s] Mode3_gating_train_vi_full_mfbe_pitch | EER=3.6383% | minDCF=0.588935 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): GATING
  Handcrafted Feature: PITCH_ONLY
  Num speakers: 1
  Trainable parameters: 9,507,392
======================================================================

Experiments (7s): 100%|██████████| 65/65 [08:17<00:00,  7.66s/it]

✅ [7s] Mode3_gating_train_vi_full_pitch_only | EER=4.0035% | minDCF=0.688494 | pairs_used=9895 | missing=0

✅ TOP RESULTS [7s] (status=ok)

,test_set,experiment,mode,feature_mode,fusion_method,checkpoint,status,eer_percent,mindcf,pairs_used,pairs_missing
39,7s,Mode3_cross_attention_train_vi_3s_mfbe_pitch,3,mfbe_pitch,cross_attention,best_model.pth,ok,3.3610,0.563801,9895,0
38,7s,Mode3_cross_attention_train_vi_3s_mfbe_only,3,mfbe_only,cross_attention,best_model.pth,ok,3.3949,0.560237,9895,0
25,7s,Mode3_concat_train_vi_3s_pitch_only,3,pitch_only,concat,best_model.pth,ok,3.5166,0.586268,9895,0
36,7s,Mode3_cross_attention_train_raw_mfbe_pitch,3,mfbe_pitch,cross_attention,best_model.pth,ok,3.5233,0.609492,9895,0
1,7s,Mode1_FBank_train_vi_3s,1,N/A,N/A,best_model.pth,ok,3.5505,0.596587,9895,0
0,7s,Mode1_FBank_train_raw,1,N/A,N/A,best_model.pth,ok,3.5505,0.608718,9895,0
32,7s,Mode3_concat_train_vi_full_mfbe_only,3,mfbe_only,concat,best_model.pth,ok,3.5572,0.595983,9895,0
49,7s,Mode3_cross_attention_train_vi_full_pitch_only,3,pitch_only,cross_attention,best_model.pth,ok,3.5978,0.603653,9895,0
4,7s,Mode1_FBank_train_vi_full,1,N/A,N/A,best_model.pth,ok,3.5978,0.642188,9895,0
34,7s,Mode3_concat_train_vi_full_pitch_only,3,pitch_only,concat,best_model.pth,ok,3.6045,0.639673,9895,0
63,7s,Mode3_gating_train_vi_full_mfbe_pitch,3,mfbe_pitch,gating,best_model.pth,ok,3.6383,0.588935,9895,0
51,7s,Mode3_gating_train_raw_mfbe_pitch,3,mfbe_pitch,gating,best_model.pth,ok,3.6383,0.620921,9895,0
57,7s,Mode3_gating_train_vi_5s_mfbe_pitch,3,mfbe_pitch,gating,best_model.pth,ok,3.6450,0.573461,9895,0
47,7s,Mode3_cross_attention_train_vi_full_mfbe_only,3,mfbe_only,cross_attention,best_model.pth,ok,3.6450,0.619952,9895,0
55,7s,Mode3_gating_train_vi_3s_pitch_only,3,pitch_only,gating,best_model.pth,ok,3.6450,0.621569,9895,0
50,7s,Mode3_gating_train_raw_mfbe_only,3,mfbe_only,gating,best_model.pth,ok,3.6450,0.651982,9895,0
21,7s,Mode3_concat_train_raw_mfbe_pitch,3,mfbe_pitch,concat,best_model.pth,ok,3.6789,0.603074,9895,0
2,7s,Mode1_FBank_train_vi_5s,1,N/A,N/A,best_model.pth,ok,3.6856,0.621323,9895,0
40,7s,Mode3_cross_attention_train_vi_3s_pitch_only,3,pitch_only,cross_attention,best_model.pth,ok,3.6856,0.623117,9895,0
23,7s,Mode3_concat_train_vi_3s_mfbe_only,3,mfbe_only,concat,best_model.pth,ok,3.7195,0.608736,9895,0

💾 [7s] Đã lưu bảng tổng hợp: outputs\experiments\inference_test_o_summary_7s.csv

====================================================================================================
ĐANG CHẠY TEST SET: vi
====================================================================================================
✅ [vi] Loaded CSV pairs: 9895 rows from D:\test_o\list_gt\test_list_gt_vi.csv

Experiments (vi):   0%|          | 0/65 [00:00<?, ?it/s]

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 1 (1=Main, 2=Handcrafted, 3=Fusion)
  Num speakers: 1
  Trainable parameters: 7,962,176
======================================================================

Experiments (vi):   2%|▏         | 1/65 [00:38<40:35, 38.05s/it]

✅ [vi] Mode1_FBank_train_raw | EER=3.0297% | minDCF=0.213967 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 1 (1=Main, 2=Handcrafted, 3=Fusion)
  Num speakers: 1
  Trainable parameters: 7,962,176
======================================================================

Experiments (vi):   3%|▎         | 2/65 [01:16<40:04, 38.16s/it]

✅ [vi] Mode1_FBank_train_vi_3s | EER=3.0229% | minDCF=0.214651 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 1 (1=Main, 2=Handcrafted, 3=Fusion)
  Num speakers: 1
  Trainable parameters: 7,962,176
======================================================================

Experiments (vi):   5%|▍         | 3/65 [01:59<41:54, 40.55s/it]

✅ [vi] Mode1_FBank_train_vi_5s | EER=3.5572% | minDCF=0.252379 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 1 (1=Main, 2=Handcrafted, 3=Fusion)
  Num speakers: 1
  Trainable parameters: 7,962,176
======================================================================

Experiments (vi):   6%|▌         | 4/65 [02:43<42:41, 41.99s/it]

✅ [vi] Mode1_FBank_train_vi_7s | EER=4.9976% | minDCF=0.312459 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 1 (1=Main, 2=Handcrafted, 3=Fusion)
  Num speakers: 1
  Trainable parameters: 7,962,176
======================================================================

Experiments (vi):   8%|▊         | 5/65 [03:28<42:50, 42.85s/it]

✅ [vi] Mode1_FBank_train_vi_full | EER=3.3610% | minDCF=0.247180 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 2 (1=Main, 2=Handcrafted, 3=Fusion)
  Handcrafted Feature: MFBE_ONLY
  Num speakers: 1
  Trainable parameters: 1,050,752
======================================================================

Experiments (vi):   9%|▉         | 6/65 [03:41<32:22, 32.92s/it]

✅ [vi] Mode2_HC_train_raw_mfbe_only | EER=64.3404% | minDCF=0.980785 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 2 (1=Main, 2=Handcrafted, 3=Fusion)
  Handcrafted Feature: MFBE_PITCH
  Num speakers: 1
  Trainable parameters: 1,051,136
======================================================================

Experiments (vi):  11%|█         | 7/65 [03:58<26:40, 27.59s/it]

✅ [vi] Mode2_HC_train_raw_mfbe_pitch | EER=61.3241% | minDCF=0.978332 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 2 (1=Main, 2=Handcrafted, 3=Fusion)
  Handcrafted Feature: PITCH_ONLY
  Num speakers: 1
  Trainable parameters: 1,020,416
======================================================================

Experiments (vi):  12%|█▏        | 8/65 [04:05<19:56, 20.98s/it]

✅ [vi] Mode2_HC_train_raw_pitch_only | EER=60.7088% | minDCF=0.979967 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 2 (1=Main, 2=Handcrafted, 3=Fusion)
  Handcrafted Feature: MFBE_ONLY
  Num speakers: 1
  Trainable parameters: 1,050,752
======================================================================

Experiments (vi):  14%|█▍        | 9/65 [04:13<15:47, 16.92s/it]

✅ [vi] Mode2_HC_train_vi_3s_mfbe_only | EER=64.8813% | minDCF=0.978741 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 2 (1=Main, 2=Handcrafted, 3=Fusion)
  Handcrafted Feature: MFBE_PITCH
  Num speakers: 1
  Trainable parameters: 1,051,136
======================================================================

Experiments (vi):  15%|█▌        | 10/65 [04:21<12:54, 14.08s/it]

✅ [vi] Mode2_HC_train_vi_3s_mfbe_pitch | EER=60.5464% | minDCF=0.975470 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 2 (1=Main, 2=Handcrafted, 3=Fusion)
  Handcrafted Feature: PITCH_ONLY
  Num speakers: 1
  Trainable parameters: 1,020,416
======================================================================

Experiments (vi):  17%|█▋        | 11/65 [04:27<10:29, 11.65s/it]

✅ [vi] Mode2_HC_train_vi_3s_pitch_only | EER=60.5059% | minDCF=0.982011 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 2 (1=Main, 2=Handcrafted, 3=Fusion)
  Handcrafted Feature: MFBE_ONLY
  Num speakers: 1
  Trainable parameters: 1,050,752
======================================================================

Experiments (vi):  18%|█▊        | 12/65 [04:35<09:19, 10.56s/it]

✅ [vi] Mode2_HC_train_vi_5s_mfbe_only | EER=64.0563% | minDCF=0.977923 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 2 (1=Main, 2=Handcrafted, 3=Fusion)
  Handcrafted Feature: MFBE_PITCH
  Num speakers: 1
  Trainable parameters: 1,051,136
======================================================================

Experiments (vi):  20%|██        | 13/65 [04:42<08:22,  9.66s/it]

✅ [vi] Mode2_HC_train_vi_5s_mfbe_pitch | EER=65.3344% | minDCF=0.979967 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 2 (1=Main, 2=Handcrafted, 3=Fusion)
  Handcrafted Feature: PITCH_ONLY
  Num speakers: 1
  Trainable parameters: 1,020,416
======================================================================

Experiments (vi):  22%|██▏       | 14/65 [04:48<07:16,  8.56s/it]

✅ [vi] Mode2_HC_train_vi_5s_pitch_only | EER=62.4265% | minDCF=0.985691 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 2 (1=Main, 2=Handcrafted, 3=Fusion)
  Handcrafted Feature: MFBE_ONLY
  Num speakers: 1
  Trainable parameters: 1,050,752
======================================================================

Experiments (vi):  23%|██▎       | 15/65 [04:56<06:57,  8.34s/it]

✅ [vi] Mode2_HC_train_vi_7s_mfbe_only | EER=66.5179% | minDCF=0.983238 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 2 (1=Main, 2=Handcrafted, 3=Fusion)
  Handcrafted Feature: MFBE_PITCH
  Num speakers: 1
  Trainable parameters: 1,051,136
======================================================================

Experiments (vi):  25%|██▍       | 16/65 [05:04<06:37,  8.11s/it]

✅ [vi] Mode2_HC_train_vi_7s_mfbe_pitch | EER=66.2811% | minDCF=0.981194 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 2 (1=Main, 2=Handcrafted, 3=Fusion)
  Handcrafted Feature: PITCH_ONLY
  Num speakers: 1
  Trainable parameters: 1,020,416
======================================================================

Experiments (vi):  26%|██▌       | 17/65 [05:10<05:59,  7.50s/it]

✅ [vi] Mode2_HC_train_vi_7s_pitch_only | EER=58.7476% | minDCF=0.981603 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 2 (1=Main, 2=Handcrafted, 3=Fusion)
  Handcrafted Feature: MFBE_ONLY
  Num speakers: 1
  Trainable parameters: 1,050,752
======================================================================

Experiments (vi):  28%|██▊       | 18/65 [05:18<05:56,  7.59s/it]

✅ [vi] Mode2_HC_train_vi_full_mfbe_only | EER=63.5355% | minDCF=0.980376 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 2 (1=Main, 2=Handcrafted, 3=Fusion)
  Handcrafted Feature: MFBE_PITCH
  Num speakers: 1
  Trainable parameters: 1,051,136
======================================================================

Experiments (vi):  29%|██▉       | 19/65 [05:25<05:49,  7.59s/it]

✅ [vi] Mode2_HC_train_vi_full_mfbe_pitch | EER=63.4949% | minDCF=0.979558 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 2 (1=Main, 2=Handcrafted, 3=Fusion)
  Handcrafted Feature: PITCH_ONLY
  Num speakers: 1
  Trainable parameters: 1,020,416
======================================================================

Experiments (vi):  31%|███       | 20/65 [05:31<05:21,  7.14s/it]

✅ [vi] Mode2_HC_train_vi_full_pitch_only | EER=59.2412% | minDCF=0.978332 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CONCAT
  Handcrafted Feature: MFBE_ONLY
  Num speakers: 1
  Trainable parameters: 9,537,728
======================================================================

Experiments (vi):  32%|███▏      | 21/65 [06:24<15:10, 20.68s/it]

✅ [vi] Mode3_concat_train_raw_mfbe_only | EER=3.5099% | minDCF=0.229564 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CONCAT
  Handcrafted Feature: MFBE_PITCH
  Num speakers: 1
  Trainable parameters: 9,538,112
======================================================================

Experiments (vi):  34%|███▍      | 22/65 [07:16<21:36, 30.16s/it]

✅ [vi] Mode3_concat_train_raw_mfbe_pitch | EER=3.7601% | minDCF=0.225103 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CONCAT
  Handcrafted Feature: PITCH_ONLY
  Num speakers: 1
  Trainable parameters: 9,507,392
======================================================================

Experiments (vi):  35%|███▌      | 23/65 [08:06<25:19, 36.18s/it]

✅ [vi] Mode3_concat_train_raw_pitch_only | EER=3.3949% | minDCF=0.272119 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CONCAT
  Handcrafted Feature: MFBE_ONLY
  Num speakers: 1
  Trainable parameters: 9,537,728
======================================================================

Experiments (vi):  37%|███▋      | 24/65 [08:58<27:58, 40.93s/it]

✅ [vi] Mode3_concat_train_vi_3s_mfbe_only | EER=29.3974% | minDCF=0.810950 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CONCAT
  Handcrafted Feature: MFBE_PITCH
  Num speakers: 1
  Trainable parameters: 9,538,112
======================================================================

Experiments (vi):  38%|███▊      | 25/65 [09:50<29:28, 44.21s/it]

✅ [vi] Mode3_concat_train_vi_3s_mfbe_pitch | EER=24.2443% | minDCF=0.766804 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CONCAT
  Handcrafted Feature: PITCH_ONLY
  Num speakers: 1
  Trainable parameters: 9,507,392
======================================================================

Experiments (vi):  40%|████      | 26/65 [10:40<29:55, 46.05s/it]

✅ [vi] Mode3_concat_train_vi_3s_pitch_only | EER=4.7407% | minDCF=0.325133 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CONCAT
  Handcrafted Feature: MFBE_ONLY
  Num speakers: 1
  Trainable parameters: 9,537,728
======================================================================

Experiments (vi):  42%|████▏     | 27/65 [11:33<30:21, 47.94s/it]

✅ [vi] Mode3_concat_train_vi_5s_mfbe_only | EER=43.6194% | minDCF=0.908332 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CONCAT
  Handcrafted Feature: MFBE_PITCH
  Num speakers: 1
  Trainable parameters: 9,538,112
======================================================================

Experiments (vi):  43%|████▎     | 28/65 [12:25<30:18, 49.14s/it]

✅ [vi] Mode3_concat_train_vi_5s_mfbe_pitch | EER=44.7285% | minDCF=0.936364 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CONCAT
  Handcrafted Feature: PITCH_ONLY
  Num speakers: 1
  Trainable parameters: 9,507,392
======================================================================

Experiments (vi):  45%|████▍     | 29/65 [13:15<29:43, 49.53s/it]

✅ [vi] Mode3_concat_train_vi_5s_pitch_only | EER=5.3966% | minDCF=0.314192 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CONCAT
  Handcrafted Feature: MFBE_ONLY
  Num speakers: 1
  Trainable parameters: 9,537,728
======================================================================

Experiments (vi):  46%|████▌     | 30/65 [14:07<29:20, 50.29s/it]

✅ [vi] Mode3_concat_train_vi_7s_mfbe_only | EER=62.3453% | minDCF=0.951758 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CONCAT
  Handcrafted Feature: MFBE_PITCH
  Num speakers: 1
  Trainable parameters: 9,538,112
======================================================================

Experiments (vi):  48%|████▊     | 31/65 [14:59<28:47, 50.80s/it]

✅ [vi] Mode3_concat_train_vi_7s_mfbe_pitch | EER=64.2726% | minDCF=0.954309 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CONCAT
  Handcrafted Feature: PITCH_ONLY
  Num speakers: 1
  Trainable parameters: 9,507,392
======================================================================

Experiments (vi):  49%|████▉     | 32/65 [15:49<27:47, 50.54s/it]

✅ [vi] Mode3_concat_train_vi_7s_pitch_only | EER=18.6853% | minDCF=0.697455 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CONCAT
  Handcrafted Feature: MFBE_ONLY
  Num speakers: 1
  Trainable parameters: 9,537,728
======================================================================

Experiments (vi):  51%|█████     | 33/65 [16:40<27:06, 50.82s/it]

✅ [vi] Mode3_concat_train_vi_full_mfbe_only | EER=4.2131% | minDCF=0.281211 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CONCAT
  Handcrafted Feature: MFBE_PITCH
  Num speakers: 1
  Trainable parameters: 9,538,112
======================================================================

Experiments (vi):  52%|█████▏    | 34/65 [17:32<26:20, 50.98s/it]

✅ [vi] Mode3_concat_train_vi_full_mfbe_pitch | EER=2.8606% | minDCF=0.227147 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CONCAT
  Handcrafted Feature: PITCH_ONLY
  Num speakers: 1
  Trainable parameters: 9,507,392
======================================================================

Experiments (vi):  54%|█████▍    | 35/65 [18:22<25:17, 50.60s/it]

✅ [vi] Mode3_concat_train_vi_full_pitch_only | EER=3.7601% | minDCF=0.237954 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CROSS_ATTENTION
  Handcrafted Feature: MFBE_ONLY
  Num speakers: 1
  Trainable parameters: 9,801,920
======================================================================

Experiments (vi):  55%|█████▌    | 36/65 [19:14<24:47, 51.29s/it]

✅ [vi] Mode3_cross_attention_train_raw_mfbe_only | EER=3.1041% | minDCF=0.240017 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CROSS_ATTENTION
  Handcrafted Feature: MFBE_PITCH
  Num speakers: 1
  Trainable parameters: 9,802,304
======================================================================

Experiments (vi):  57%|█████▋    | 37/65 [20:07<24:09, 51.77s/it]

✅ [vi] Mode3_cross_attention_train_raw_mfbe_pitch | EER=3.9697% | minDCF=0.244825 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CROSS_ATTENTION
  Handcrafted Feature: PITCH_ONLY
  Num speakers: 1
  Trainable parameters: 9,771,584
======================================================================

Experiments (vi):  58%|█████▊    | 38/65 [20:59<23:14, 51.66s/it]

✅ [vi] Mode3_cross_attention_train_raw_pitch_only | EER=3.6789% | minDCF=0.237289 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CROSS_ATTENTION
  Handcrafted Feature: MFBE_ONLY
  Num speakers: 1
  Trainable parameters: 9,801,920
======================================================================

Experiments (vi):  60%|██████    | 39/65 [21:52<22:34, 52.08s/it]

✅ [vi] Mode3_cross_attention_train_vi_3s_mfbe_only | EER=2.8673% | minDCF=0.215780 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CROSS_ATTENTION
  Handcrafted Feature: MFBE_PITCH
  Num speakers: 1
  Trainable parameters: 9,802,304
======================================================================

Experiments (vi):  62%|██████▏   | 40/65 [22:45<21:48, 52.33s/it]

✅ [vi] Mode3_cross_attention_train_vi_3s_mfbe_pitch | EER=3.1514% | minDCF=0.230356 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CROSS_ATTENTION
  Handcrafted Feature: PITCH_ONLY
  Num speakers: 1
  Trainable parameters: 9,771,584
======================================================================

Experiments (vi):  63%|██████▎   | 41/65 [23:36<20:49, 52.04s/it]

✅ [vi] Mode3_cross_attention_train_vi_3s_pitch_only | EER=3.0635% | minDCF=0.216518 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CROSS_ATTENTION
  Handcrafted Feature: MFBE_ONLY
  Num speakers: 1
  Trainable parameters: 9,801,920
======================================================================

Experiments (vi):  65%|██████▍   | 42/65 [24:29<20:03, 52.33s/it]

✅ [vi] Mode3_cross_attention_train_vi_5s_mfbe_only | EER=3.2325% | minDCF=0.225867 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CROSS_ATTENTION
  Handcrafted Feature: MFBE_PITCH
  Num speakers: 1
  Trainable parameters: 9,802,304
======================================================================

Experiments (vi):  66%|██████▌   | 43/65 [25:22<19:15, 52.53s/it]

✅ [vi] Mode3_cross_attention_train_vi_5s_mfbe_pitch | EER=3.5099% | minDCF=0.256023 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CROSS_ATTENTION
  Handcrafted Feature: PITCH_ONLY
  Num speakers: 1
  Trainable parameters: 9,771,584
======================================================================

Experiments (vi):  68%|██████▊   | 44/65 [26:12<18:06, 51.75s/it]

✅ [vi] Mode3_cross_attention_train_vi_5s_pitch_only | EER=3.5166% | minDCF=0.235928 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CROSS_ATTENTION
  Handcrafted Feature: MFBE_ONLY
  Num speakers: 1
  Trainable parameters: 9,801,920
======================================================================

Experiments (vi):  69%|██████▉   | 45/65 [27:06<17:28, 52.41s/it]

✅ [vi] Mode3_cross_attention_train_vi_7s_mfbe_only | EER=25.2249% | minDCF=0.837000 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CROSS_ATTENTION
  Handcrafted Feature: MFBE_PITCH
  Num speakers: 1
  Trainable parameters: 9,802,304
======================================================================

Experiments (vi):  71%|███████   | 46/65 [28:13<17:59, 56.84s/it]

✅ [vi] Mode3_cross_attention_train_vi_7s_mfbe_pitch | EER=25.5089% | minDCF=0.882123 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CROSS_ATTENTION
  Handcrafted Feature: PITCH_ONLY
  Num speakers: 1
  Trainable parameters: 9,771,584
======================================================================

Experiments (vi):  72%|███████▏  | 47/65 [29:05<16:34, 55.23s/it]

✅ [vi] Mode3_cross_attention_train_vi_7s_pitch_only | EER=11.6860% | minDCF=0.546976 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CROSS_ATTENTION
  Handcrafted Feature: MFBE_ONLY
  Num speakers: 1
  Trainable parameters: 9,801,920
======================================================================

Experiments (vi):  74%|███████▍  | 48/65 [29:56<15:16, 53.93s/it]

✅ [vi] Mode3_cross_attention_train_vi_full_mfbe_only | EER=3.4760% | minDCF=0.250140 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CROSS_ATTENTION
  Handcrafted Feature: MFBE_PITCH
  Num speakers: 1
  Trainable parameters: 9,802,304
======================================================================

Experiments (vi):  75%|███████▌  | 49/65 [30:42<13:49, 51.84s/it]

✅ [vi] Mode3_cross_attention_train_vi_full_mfbe_pitch | EER=3.0635% | minDCF=0.215024 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): CROSS_ATTENTION
  Handcrafted Feature: PITCH_ONLY
  Num speakers: 1
  Trainable parameters: 9,771,584
======================================================================

Experiments (vi):  77%|███████▋  | 50/65 [31:31<12:42, 50.80s/it]

✅ [vi] Mode3_cross_attention_train_vi_full_pitch_only | EER=3.3543% | minDCF=0.217433 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): GATING
  Handcrafted Feature: MFBE_ONLY
  Num speakers: 1
  Trainable parameters: 9,537,728
======================================================================

Experiments (vi):  78%|███████▊  | 51/65 [32:28<12:19, 52.84s/it]

✅ [vi] Mode3_gating_train_raw_mfbe_only | EER=4.2470% | minDCF=0.265986 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): GATING
  Handcrafted Feature: MFBE_PITCH
  Num speakers: 1
  Trainable parameters: 9,538,112
======================================================================

Experiments (vi):  80%|████████  | 52/65 [33:49<13:13, 61.07s/it]

✅ [vi] Mode3_gating_train_raw_mfbe_pitch | EER=2.9824% | minDCF=0.236977 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): GATING
  Handcrafted Feature: PITCH_ONLY
  Num speakers: 1
  Trainable parameters: 9,507,392
======================================================================

Experiments (vi):  82%|████████▏ | 53/65 [34:46<11:57, 59.81s/it]

✅ [vi] Mode3_gating_train_raw_pitch_only | EER=8.6698% | minDCF=0.463061 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): GATING
  Handcrafted Feature: MFBE_ONLY
  Num speakers: 1
  Trainable parameters: 9,537,728
======================================================================

Experiments (vi):  83%|████████▎ | 54/65 [36:06<12:04, 65.87s/it]

✅ [vi] Mode3_gating_train_vi_3s_mfbe_only | EER=19.9500% | minDCF=0.706616 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): GATING
  Handcrafted Feature: MFBE_PITCH
  Num speakers: 1
  Trainable parameters: 9,538,112
======================================================================

Experiments (vi):  85%|████████▍ | 55/65 [37:27<11:45, 70.58s/it]

✅ [vi] Mode3_gating_train_vi_3s_mfbe_pitch | EER=25.8741% | minDCF=0.737448 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): GATING
  Handcrafted Feature: PITCH_ONLY
  Num speakers: 1
  Trainable parameters: 9,507,392
======================================================================

Experiments (vi):  86%|████████▌ | 56/65 [38:18<09:42, 64.76s/it]

✅ [vi] Mode3_gating_train_vi_3s_pitch_only | EER=3.8818% | minDCF=0.261391 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): GATING
  Handcrafted Feature: MFBE_ONLY
  Num speakers: 1
  Trainable parameters: 9,537,728
======================================================================

Experiments (vi):  88%|████████▊ | 57/65 [39:46<09:31, 71.48s/it]

✅ [vi] Mode3_gating_train_vi_5s_mfbe_only | EER=40.7182% | minDCF=0.899782 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): GATING
  Handcrafted Feature: MFBE_PITCH
  Num speakers: 1
  Trainable parameters: 9,538,112
======================================================================

Experiments (vi):  89%|████████▉ | 58/65 [41:00<08:25, 72.27s/it]

✅ [vi] Mode3_gating_train_vi_5s_mfbe_pitch | EER=26.9426% | minDCF=0.820940 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): GATING
  Handcrafted Feature: PITCH_ONLY
  Num speakers: 1
  Trainable parameters: 9,507,392
======================================================================

Experiments (vi):  91%|█████████ | 59/65 [41:58<06:48, 68.14s/it]

✅ [vi] Mode3_gating_train_vi_5s_pitch_only | EER=4.9841% | minDCF=0.340064 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): GATING
  Handcrafted Feature: MFBE_ONLY
  Num speakers: 1
  Trainable parameters: 9,537,728
======================================================================

Experiments (vi):  92%|█████████▏| 60/65 [43:15<05:53, 70.78s/it]

✅ [vi] Mode3_gating_train_vi_7s_mfbe_only | EER=54.5817% | minDCF=0.909301 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): GATING
  Handcrafted Feature: MFBE_PITCH
  Num speakers: 1
  Trainable parameters: 9,538,112
======================================================================

Experiments (vi):  94%|█████████▍| 61/65 [44:30<04:47, 71.95s/it]

✅ [vi] Mode3_gating_train_vi_7s_mfbe_pitch | EER=57.0704% | minDCF=0.930170 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): GATING
  Handcrafted Feature: PITCH_ONLY
  Num speakers: 1
  Trainable parameters: 9,507,392
======================================================================

Experiments (vi):  95%|█████████▌| 62/65 [45:35<03:30, 70.02s/it]

✅ [vi] Mode3_gating_train_vi_7s_pitch_only | EER=10.2185% | minDCF=0.510333 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): GATING
  Handcrafted Feature: MFBE_ONLY
  Num speakers: 1
  Trainable parameters: 9,537,728
======================================================================

Experiments (vi):  97%|█████████▋| 63/65 [46:43<02:18, 69.33s/it]

✅ [vi] Mode3_gating_train_vi_full_mfbe_only | EER=4.9908% | minDCF=0.315828 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): GATING
  Handcrafted Feature: MFBE_PITCH
  Num speakers: 1
  Trainable parameters: 9,538,112
======================================================================

Experiments (vi):  98%|█████████▊| 64/65 [47:55<01:10, 70.23s/it]

✅ [vi] Mode3_gating_train_vi_full_mfbe_pitch | EER=5.4778% | minDCF=0.293298 | pairs_used=9895 | missing=0

======================================================================
Khởi tạo mô hình thành công (Hybrid ECAPA-TDNN)
  Mode: 3 (1=Main, 2=Handcrafted, 3=Fusion)
  Fusion method (Late Fusion): GATING
  Handcrafted Feature: PITCH_ONLY
  Num speakers: 1
  Trainable parameters: 9,507,392
======================================================================

Experiments (vi): 100%|██████████| 65/65 [49:02<00:00, 45.26s/it]

✅ [vi] Mode3_gating_train_vi_full_pitch_only | EER=3.3137% | minDCF=0.242611 | pairs_used=9895 | missing=0

✅ TOP RESULTS [vi] (status=ok)

,test_set,experiment,mode,feature_mode,fusion_method,checkpoint,status,eer_percent,mindcf,pairs_used,pairs_missing
33,vi,Mode3_concat_train_vi_full_mfbe_pitch,3,mfbe_pitch,concat,best_model.pth,ok,2.8606,0.227147,9895,0
38,vi,Mode3_cross_attention_train_vi_3s_mfbe_only,3,mfbe_only,cross_attention,best_model.pth,ok,2.8673,0.215780,9895,0
51,vi,Mode3_gating_train_raw_mfbe_pitch,3,mfbe_pitch,gating,best_model.pth,ok,2.9824,0.236977,9895,0
1,vi,Mode1_FBank_train_vi_3s,1,N/A,N/A,best_model.pth,ok,3.0229,0.214651,9895,0
0,vi,Mode1_FBank_train_raw,1,N/A,N/A,best_model.pth,ok,3.0297,0.213967,9895,0
48,vi,Mode3_cross_attention_train_vi_full_mfbe_pitch,3,mfbe_pitch,cross_attention,best_model.pth,ok,3.0635,0.215024,9895,0
40,vi,Mode3_cross_attention_train_vi_3s_pitch_only,3,pitch_only,cross_attention,best_model.pth,ok,3.0635,0.216518,9895,0
35,vi,Mode3_cross_attention_train_raw_mfbe_only,3,mfbe_only,cross_attention,best_model.pth,ok,3.1041,0.240017,9895,0
39,vi,Mode3_cross_attention_train_vi_3s_mfbe_pitch,3,mfbe_pitch,cross_attention,best_model.pth,ok,3.1514,0.230356,9895,0
41,vi,Mode3_cross_attention_train_vi_5s_mfbe_only,3,mfbe_only,cross_attention,best_model.pth,ok,3.2325,0.225867,9895,0
64,vi,Mode3_gating_train_vi_full_pitch_only,3,pitch_only,gating,best_model.pth,ok,3.3137,0.242611,9895,0
49,vi,Mode3_cross_attention_train_vi_full_pitch_only,3,pitch_only,cross_attention,best_model.pth,ok,3.3543,0.217433,9895,0
4,vi,Mode1_FBank_train_vi_full,1,N/A,N/A,best_model.pth,ok,3.3610,0.247180,9895,0
22,vi,Mode3_concat_train_raw_pitch_only,3,pitch_only,concat,best_model.pth,ok,3.3949,0.272119,9895,0
47,vi,Mode3_cross_attention_train_vi_full_mfbe_only,3,mfbe_only,cross_attention,best_model.pth,ok,3.4760,0.250140,9895,0
20,vi,Mode3_concat_train_raw_mfbe_only,3,mfbe_only,concat,best_model.pth,ok,3.5099,0.229564,9895,0
42,vi,Mode3_cross_attention_train_vi_5s_mfbe_pitch,3,mfbe_pitch,cross_attention,best_model.pth,ok,3.5099,0.256023,9895,0
43,vi,Mode3_cross_attention_train_vi_5s_pitch_only,3,pitch_only,cross_attention,best_model.pth,ok,3.5166,0.235928,9895,0
2,vi,Mode1_FBank_train_vi_5s,1,N/A,N/A,best_model.pth,ok,3.5572,0.252379,9895,0
37,vi,Mode3_cross_attention_train_raw_pitch_only,3,pitch_only,cross_attention,best_model.pth,ok,3.6789,0.237289,9895,0

💾 [vi] Đã lưu bảng tổng hợp: outputs\experiments\inference_test_o_summary_vi.csv

✅ TOP RESULTS ALL TEST SETS (status=ok, sort by EER asc)

,test_set,experiment,mode,feature_mode,fusion_method,checkpoint,status,eer_percent,mindcf,pairs_used,pairs_missing
293,vi,Mode3_concat_train_vi_full_mfbe_pitch,3,mfbe_pitch,concat,best_model.pth,ok,2.8606,0.227147,9895,0
298,vi,Mode3_cross_attention_train_vi_3s_mfbe_only,3,mfbe_only,cross_attention,best_model.pth,ok,2.8673,0.215780,9895,0
311,vi,Mode3_gating_train_raw_mfbe_pitch,3,mfbe_pitch,gating,best_model.pth,ok,2.9824,0.236977,9895,0
261,vi,Mode1_FBank_train_vi_3s,1,N/A,N/A,best_model.pth,ok,3.0229,0.214651,9895,0
260,vi,Mode1_FBank_train_raw,1,N/A,N/A,best_model.pth,ok,3.0297,0.213967,9895,0
308,vi,Mode3_cross_attention_train_vi_full_mfbe_pitch,3,mfbe_pitch,cross_attention,best_model.pth,ok,3.0635,0.215024,9895,0
300,vi,Mode3_cross_attention_train_vi_3s_pitch_only,3,pitch_only,cross_attention,best_model.pth,ok,3.0635,0.216518,9895,0
295,vi,Mode3_cross_attention_train_raw_mfbe_only,3,mfbe_only,cross_attention,best_model.pth,ok,3.1041,0.240017,9895,0
299,vi,Mode3_cross_attention_train_vi_3s_mfbe_pitch,3,mfbe_pitch,cross_attention,best_model.pth,ok,3.1514,0.230356,9895,0
301,vi,Mode3_cross_attention_train_vi_5s_mfbe_only,3,mfbe_only,cross_attention,best_model.pth,ok,3.2325,0.225867,9895,0
324,vi,Mode3_gating_train_vi_full_pitch_only,3,pitch_only,gating,best_model.pth,ok,3.3137,0.242611,9895,0
309,vi,Mode3_cross_attention_train_vi_full_pitch_only,3,pitch_only,cross_attention,best_model.pth,ok,3.3543,0.217433,9895,0
264,vi,Mode1_FBank_train_vi_full,1,N/A,N/A,best_model.pth,ok,3.3610,0.247180,9895,0
234,7s,Mode3_cross_attention_train_vi_3s_mfbe_pitch,3,mfbe_pitch,cross_attention,best_model.pth,ok,3.3610,0.563801,9895,0
282,vi,Mode3_concat_train_raw_pitch_only,3,pitch_only,concat,best_model.pth,ok,3.3949,0.272119,9895,0
233,7s,Mode3_cross_attention_train_vi_3s_mfbe_only,3,mfbe_only,cross_attention,best_model.pth,ok,3.3949,0.560237,9895,0
307,vi,Mode3_cross_attention_train_vi_full_mfbe_only,3,mfbe_only,cross_attention,best_model.pth,ok,3.4760,0.250140,9895,0
280,vi,Mode3_concat_train_raw_mfbe_only,3,mfbe_only,concat,best_model.pth,ok,3.5099,0.229564,9895,0
302,vi,Mode3_cross_attention_train_vi_5s_mfbe_pitch,3,mfbe_pitch,cross_attention,best_model.pth,ok,3.5099,0.256023,9895,0
303,vi,Mode3_cross_attention_train_vi_5s_pitch_only,3,pitch_only,cross_attention,best_model.pth,ok,3.5166,0.235928,9895,0
220,7s,Mode3_concat_train_vi_3s_pitch_only,3,pitch_only,concat,best_model.pth,ok,3.5166,0.586268,9895,0
231,7s,Mode3_cross_attention_train_raw_mfbe_pitch,3,mfbe_pitch,cross_attention,best_model.pth,ok,3.5233,0.609492,9895,0
196,7s,Mode1_FBank_train_vi_3s,1,N/A,N/A,best_model.pth,ok,3.5505,0.596587,9895,0
195,7s,Mode1_FBank_train_raw,1,N/A,N/A,best_model.pth,ok,3.5505,0.608718,9895,0
262,vi,Mode1_FBank_train_vi_5s,1,N/A,N/A,best_model.pth,ok,3.5572,0.252379,9895,0
227,7s,Mode3_concat_train_vi_full_mfbe_only,3,mfbe_only,concat,best_model.pth,ok,3.5572,0.595983,9895,0
244,7s,Mode3_cross_attention_train_vi_full_pitch_only,3,pitch_only,cross_attention,best_model.pth,ok,3.5978,0.603653,9895,0
199,7s,Mode1_FBank_train_vi_full,1,N/A,N/A,best_model.pth,ok,3.5978,0.642188,9895,0
229,7s,Mode3_concat_train_vi_full_pitch_only,3,pitch_only,concat,best_model.pth,ok,3.6045,0.639673,9895,0
258,7s,Mode3_gating_train_vi_full_mfbe_pitch,3,mfbe_pitch,gating,best_model.pth,ok,3.6383,0.588935,9895,0

💾 Đã lưu bảng tổng hợp toàn bộ test sets: outputs\experiments\inference_test_o_summary_all_sets.csv

## 5. Gating Analysis (Only for Mode 3 + Gating)

In [ ]:
from train import analyze_gating_behavior
import matplotlib.image as mpimg

# Kiểm tra điều kiện để chạy phân tích
if args.mode == 3 and args.fusion_method == "gating":
    print("Đang thực hiện phân tích cơ chế Gating trên tập Test...")
    
    # Gọi hàm phân tích từ train.py
    # Lưu ý: Hàm này trả về 2 giá trị: gates (trọng số PTM) và labels
    gates, labels = analyze_gating_behavior(model, test_loader, device, exp_dir)
    
    # Hiển thị biểu đồ phân phối trọng số đã được lưu
    gate_plot_path = os.path.join(exp_dir, "gating_analysis", "gate_distribution.png")
    if os.path.exists(gate_plot_path):
        plt.figure(figsize=(10, 6))
        img = mpimg.imread(gate_plot_path)
        plt.imshow(img)
        plt.axis('off')
        plt.title("Phân phối trọng số Gating (Trục X > 0.5 ưu tiên PTM, < 0.5 ưu tiên Handcrafted)")
        plt.show()
        
    # In thông tin thống kê tóm tắt
    ptm_wins = np.sum(gates > 0.5)
    hc_wins = np.sum(gates <= 0.5)
    print(f"Thống kê nhanh:")
    print(f"   - Số lần ưu tiên PTM (WavLM/HuBERT): {ptm_wins} ({100*ptm_wins/len(gates):.2f}%)")
    print(f"   - Số lần ưu tiên Handcrafted (MFCC/Pitch): {hc_wins} ({100*hc_wins/len(gates):.2f}%)")
else:
    print("ℹChế độ hiện tại không sử dụng Gating. Bỏ qua bước phân tích này.")

## 6. Train/Val Experiment Comparison

In [4]:
import pandas as pd
import os
import json

# List all experiments
exp_base_dir = "./outputs/experiments"
if os.path.exists(exp_base_dir):
    experiments = []
    for exp_name_dir in sorted(os.listdir(exp_base_dir)):
        exp_path = os.path.join(exp_base_dir, exp_name_dir)
        results_file = os.path.join(exp_path, "results.json")
        if os.path.exists(results_file):
            with open(results_file, "r") as f:
                data = json.load(f)
                config = data.get("config", {})
                metrics = data.get("best_metrics", {})
                experiments.append({
                    "Experiment": exp_name_dir,
                    "Mode": config.get("mode", ""),
                    "Fusion": config.get("fusion_method", "N/A"),
                    "Feature": config.get("feature_mode", "N/A"),
                    "Best EER": f"{metrics.get('best_val_eer', 0):.2f}%",  # Đã đổi từ Loss sang EER
                    "MinDCF": f"{metrics.get('best_val_mindcf', 0):.4f}",
                    "Epochs": data.get("epochs_trained", 0),
                })
    
    if experiments:
        df = pd.DataFrame(experiments)
        print("\n" + "="*120)
        print("EXPERIMENT COMPARISON")
        print("="*120)
        print(df.to_string(index=False))
        print("="*120)
    else:
        print("No experiments found.")
else:
    print(f"Directory {exp_base_dir} does not exist yet.")

========================================================================================================================
EXPERIMENT COMPARISON
========================================================================================================================
                                    Experiment  Mode          Fusion    Feature Best EER MinDCF  Epochs
                         Mode1_FBank_train_raw     1             N/A        N/A    8.35% 0.2158      22
                       Mode1_FBank_train_vi_3s     1             N/A        N/A    7.38% 0.1690      16
                       Mode1_FBank_train_vi_5s     1             N/A        N/A    5.07% 0.1267      16
                       Mode1_FBank_train_vi_7s     1             N/A        N/A    7.82% 0.1730      16
                     Mode1_FBank_train_vi_full     1             N/A        N/A    7.00% 0.2407      15
                  Mode2_HC_train_raw_mfbe_only     2             N/A  mfbe_only   11.50% 0.5378      18
                 Mode2_HC_train_raw_mfbe_pitch     2             N/A mfbe_pitch   11.08% 0.4001      22
                 Mode2_HC_train_raw_pitch_only     2             N/A pitch_only   33.23% 0.9150      12
                Mode2_HC_train_vi_3s_mfbe_only     2             N/A  mfbe_only   10.03% 0.2904      12
               Mode2_HC_train_vi_3s_mfbe_pitch     2             N/A mfbe_pitch    9.60% 0.2314      20
               Mode2_HC_train_vi_3s_pitch_only     2             N/A pitch_only   27.64% 0.9222      13
                Mode2_HC_train_vi_5s_mfbe_only     2             N/A  mfbe_only    5.49% 0.1592      19
               Mode2_HC_train_vi_5s_mfbe_pitch     2             N/A mfbe_pitch    6.31% 0.1301      18
               Mode2_HC_train_vi_5s_pitch_only     2             N/A pitch_only   24.05% 0.8850      13
                Mode2_HC_train_vi_7s_mfbe_only     2             N/A  mfbe_only   10.04% 0.2956      13
               Mode2_HC_train_vi_7s_mfbe_pitch     2             N/A mfbe_pitch   10.04% 0.3115      12
               Mode2_HC_train_vi_7s_pitch_only     2             N/A pitch_only   26.48% 0.7794      23
              Mode2_HC_train_vi_full_mfbe_only     2             N/A  mfbe_only    9.46% 0.3131      18
             Mode2_HC_train_vi_full_mfbe_pitch     2             N/A mfbe_pitch    9.39% 0.3409      18
             Mode2_HC_train_vi_full_pitch_only     2             N/A pitch_only   27.59% 0.9438      10
              Mode3_concat_train_raw_mfbe_only     3          concat  mfbe_only    8.04% 0.2366      13
             Mode3_concat_train_raw_mfbe_pitch     3          concat mfbe_pitch    7.97% 0.2430      26
             Mode3_concat_train_raw_pitch_only     3          concat pitch_only    8.83% 0.2503       9
            Mode3_concat_train_vi_3s_mfbe_only     3          concat  mfbe_only    7.73% 0.2071      14
           Mode3_concat_train_vi_3s_mfbe_pitch     3          concat mfbe_pitch    8.60% 0.1503      19
           Mode3_concat_train_vi_3s_pitch_only     3          concat pitch_only    8.79% 0.2045      11
            Mode3_concat_train_vi_5s_mfbe_only     3          concat  mfbe_only    6.12% 0.1304      12
           Mode3_concat_train_vi_5s_mfbe_pitch     3          concat mfbe_pitch    5.97% 0.1060      15
           Mode3_concat_train_vi_5s_pitch_only     3          concat pitch_only    5.90% 0.0817      17
            Mode3_concat_train_vi_7s_mfbe_only     3          concat  mfbe_only    8.15% 0.1845      16
           Mode3_concat_train_vi_7s_mfbe_pitch     3          concat mfbe_pitch   10.79% 0.1946       9
           Mode3_concat_train_vi_7s_pitch_only     3          concat pitch_only    9.01% 0.1874      13
          Mode3_concat_train_vi_full_mfbe_only     3          concat  mfbe_only    6.27% 0.3267      11
         Mode3_concat_train_vi_full_mfbe_pitch     3          concat mfbe_pitch    7.04% 0.3027      19
         Mode3_concat_train_vi_full_pitch_only     3          concat pitch_only    8.08% 0.3413      13
     Mode3_cross_attention_train_raw_mfbe_only     3 cross_attention  mfbe_only    7.97% 0.1802      15
    Mode3_cross_attention_train_raw_mfbe_pitch     3 cross_attention mfbe_pitch    8.07% 0.2437      19
    Mode3_cross_attention_train_raw_pitch_only     3 cross_attention pitch_only    8.83% 0.2297      11
   Mode3_cross_attention_train_vi_3s_mfbe_only     3 cross_attention  mfbe_only    7.73% 0.1717      17
  Mode3_cross_attention_train_vi_3s_mfbe_pitch     3 cross_attention mfbe_pitch    8.60% 0.1604      15
  Mode3_cross_attention_train_vi_3s_pitch_only     3 cross_attention pitch_only    7.73% 0.1414      14
   Mode3_cross_attention_train_vi_5s_mfbe_only     3 cross_attention  mfbe_only    5.83% 0.1074      21
  Mode3_cross_attention_train_vi_5s_mfbe_pitch     3 cross_attention mfbe_pitch    5.97% 0.1160      13
  Mode3_cross_attention_train_vi_5s_pitch_only     3 cross_attention pitch_only    5.19% 0.1404      14
   Mode3_cross_attention_train_vi_7s_mfbe_only     3 cross_attention  mfbe_only    7.93% 0.1388      22
  Mode3_cross_attention_train_vi_7s_mfbe_pitch     3 cross_attention mfbe_pitch    9.08% 0.2060      11
  Mode3_cross_attention_train_vi_7s_pitch_only     3 cross_attention pitch_only    9.15% 0.1803      13
 Mode3_cross_attention_train_vi_full_mfbe_only     3 cross_attention  mfbe_only    6.84% 0.3013      14
Mode3_cross_attention_train_vi_full_mfbe_pitch     3 cross_attention mfbe_pitch    7.68% 0.2613      20
Mode3_cross_attention_train_vi_full_pitch_only     3 cross_attention pitch_only    7.11% 0.2373      17
              Mode3_gating_train_raw_mfbe_only     3          gating  mfbe_only    9.75% 0.1981       8
             Mode3_gating_train_raw_mfbe_pitch     3          gating mfbe_pitch    9.29% 0.3081      15
             Mode3_gating_train_raw_pitch_only     3          gating pitch_only   10.61% 0.2490       9
            Mode3_gating_train_vi_3s_mfbe_only     3          gating  mfbe_only    7.92% 0.1692      14
           Mode3_gating_train_vi_3s_mfbe_pitch     3          gating mfbe_pitch    7.73% 0.1881      22
           Mode3_gating_train_vi_3s_pitch_only     3          gating pitch_only    6.24% 0.1351      10
            Mode3_gating_train_vi_5s_mfbe_only     3          gating  mfbe_only    5.90% 0.1060      11
           Mode3_gating_train_vi_5s_mfbe_pitch     3          gating mfbe_pitch    4.41% 0.0888      23
           Mode3_gating_train_vi_5s_pitch_only     3          gating pitch_only    6.12% 0.1203       8
            Mode3_gating_train_vi_7s_mfbe_only     3          gating  mfbe_only    9.01% 0.1445      16
           Mode3_gating_train_vi_7s_mfbe_pitch     3          gating mfbe_pitch   10.01% 0.1917       9
           Mode3_gating_train_vi_7s_pitch_only     3          gating pitch_only    8.93% 0.1974      21
          Mode3_gating_train_vi_full_mfbe_only     3          gating  mfbe_only    7.75% 0.3413       8
         Mode3_gating_train_vi_full_mfbe_pitch     3          gating mfbe_pitch    8.79% 0.3267      10
         Mode3_gating_train_vi_full_pitch_only     3          gating pitch_only    7.88% 0.2787      16
========================================================================================================================